// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: match_request/match_request.proto

package match_request

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchRequestService_CreateMatchRequest_FullMethodName   = "/match_request.MatchRequestService/CreateMatchRequest"
	MatchRequestService_GetUserMatchRequests_FullMethodName = "/match_request.MatchRequestService/GetUserMatchRequests"
	MatchRequestService_AcceptMatchRequest_FullMethodName   = "/match_request.MatchRequestService/AcceptMatchRequest"
	MatchRequestService_RejectMatchRequest_FullMethodName   = "/match_request.MatchRequestService/RejectMatchRequest"
	MatchRequestService_GetMatchRequest_FullMethodName      = "/match_request.MatchRequestService/GetMatchRequest"
	MatchRequestService_CancelMatchRequest_FullMethodName   = "/match_request.MatchRequestService/CancelMatchRequest"
)

// MatchRequestServiceClient is the client API for MatchRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchRequestServiceClient interface {
	CreateMatchRequest(ctx context.Context, in *CreateMatchRequestRequest, opts ...grpc.CallOption) (*CreateMatchRequestResponse, error)
	GetUserMatchRequests(ctx context.Context, in *GetUserMatchRequestsRequest, opts ...grpc.CallOption) (*GetUserMatchRequestsResponse, error)
	AcceptMatchRequest(ctx context.Context, in *AcceptMatchRequestRequest, opts ...grpc.CallOption) (*AcceptMatchRequestResponse, error)
	RejectMatchRequest(ctx context.Context, in *RejectMatchRequestRequest, opts ...grpc.CallOption) (*RejectMatchRequestResponse, error)
	GetMatchRequest(ctx context.Context, in *GetMatchRequestRequest, opts ...grpc.CallOption) (*GetMatchRequestResponse, error)
	CancelMatchRequest(ctx context.Context, in *CancelMatchRequestRequest, opts ...grpc.CallOption) (*CancelMatchRequestResponse, error)
}

type matchRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchRequestServiceClient(cc grpc.ClientConnInterface) MatchRequestServiceClient {
	return &matchRequestServiceClient{cc}
}

func (c *matchRequestServiceClient) CreateMatchRequest(ctx context.Context, in *CreateMatchRequestRequest, opts ...grpc.CallOption) (*CreateMatchRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMatchRequestResponse)
	err := c.cc.Invoke(ctx, MatchRequestService_CreateMatchRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchRequestServiceClient) GetUserMatchRequests(ctx context.Context, in *GetUserMatchRequestsRequest, opts ...grpc.CallOption) (*GetUserMatchRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMatchRequestsResponse)
	err := c.cc.Invoke(ctx, MatchRequestService_GetUserMatchRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchRequestServiceClient) AcceptMatchRequest(ctx context.Context, in *AcceptMatchRequestRequest, opts ...grpc.CallOption) (*AcceptMatchRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptMatchRequestResponse)
	err := c.cc.Invoke(ctx, MatchRequestService_AcceptMatchRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchRequestServiceClient) RejectMatchRequest(ctx context.Context, in *RejectMatchRequestRequest, opts ...grpc.CallOption) (*RejectMatchRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectMatchRequestResponse)
	err := c.cc.Invoke(ctx, MatchRequestService_RejectMatchRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchRequestServiceClient) GetMatchRequest(ctx context.Context, in *GetMatchRequestRequest, opts ...grpc.CallOption) (*GetMatchRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchRequestResponse)
	err := c.cc.Invoke(ctx, MatchRequestService_GetMatchRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchRequestServiceClient) CancelMatchRequest(ctx context.Context, in *CancelMatchRequestRequest, opts ...grpc.CallOption) (*CancelMatchRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMatchRequestResponse)
	err := c.cc.Invoke(ctx, MatchRequestService_CancelMatchRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchRequestServiceServer is the server API for MatchRequestService service.
// All implementations must embed UnimplementedMatchRequestServiceServer
// for forward compatibility.
type MatchRequestServiceServer interface {
	CreateMatchRequest(context.Context, *CreateMatchRequestRequest) (*CreateMatchRequestResponse, error)
	GetUserMatchRequests(context.Context, *GetUserMatchRequestsRequest) (*GetUserMatchRequestsResponse, error)
	AcceptMatchRequest(context.Context, *AcceptMatchRequestRequest) (*AcceptMatchRequestResponse, error)
	RejectMatchRequest(context.Context, *RejectMatchRequestRequest) (*RejectMatchRequestResponse, error)
	GetMatchRequest(context.Context, *GetMatchRequestRequest) (*GetMatchRequestResponse, error)
	CancelMatchRequest(context.Context, *CancelMatchRequestRequest) (*CancelMatchRequestResponse, error)
	mustEmbedUnimplementedMatchRequestServiceServer()
}

// UnimplementedMatchRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchRequestServiceServer struct{}

func (UnimplementedMatchRequestServiceServer) CreateMatchRequest(context.Context, *CreateMatchRequestRequest) (*CreateMatchRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMatchRequest not implemented")
}
func (UnimplementedMatchRequestServiceServer) GetUserMatchRequests(context.Context, *GetUserMatchRequestsRequest) (*GetUserMatchRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMatchRequests not implemented")
}
func (UnimplementedMatchRequestServiceServer) AcceptMatchRequest(context.Context, *AcceptMatchRequestRequest) (*AcceptMatchRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptMatchRequest not implemented")
}
func (UnimplementedMatchRequestServiceServer) RejectMatchRequest(context.Context, *RejectMatchRequestRequest) (*RejectMatchRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectMatchRequest not implemented")
}
func (UnimplementedMatchRequestServiceServer) GetMatchRequest(context.Context, *GetMatchRequestRequest) (*GetMatchRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchRequest not implemented")
}
func (UnimplementedMatchRequestServiceServer) CancelMatchRequest(context.Context, *CancelMatchRequestRequest) (*CancelMatchRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMatchRequest not implemented")
}
func (UnimplementedMatchRequestServiceServer) mustEmbedUnimplementedMatchRequestServiceServer() {}
func (UnimplementedMatchRequestServiceServer) testEmbeddedByValue()                             {}

// UnsafeMatchRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchRequestServiceServer will
// result in compilation errors.
type UnsafeMatchRequestServiceServer interface {
	mustEmbedUnimplementedMatchRequestServiceServer()
}

func RegisterMatchRequestServiceServer(s grpc.ServiceRegistrar, srv MatchRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchRequestService_ServiceDesc, srv)
}

func _MatchRequestService_CreateMatchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchRequestServiceServer).CreateMatchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchRequestService_CreateMatchRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchRequestServiceServer).CreateMatchRequest(ctx, req.(*CreateMatchRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchRequestService_GetUserMatchRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMatchRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchRequestServiceServer).GetUserMatchRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchRequestService_GetUserMatchRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchRequestServiceServer).GetUserMatchRequests(ctx, req.(*GetUserMatchRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchRequestService_AcceptMatchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMatchRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchRequestServiceServer).AcceptMatchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchRequestService_AcceptMatchRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchRequestServiceServer).AcceptMatchRequest(ctx, req.(*AcceptMatchRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchRequestService_RejectMatchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectMatchRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchRequestServiceServer).RejectMatchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchRequestService_RejectMatchRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchRequestServiceServer).RejectMatchRequest(ctx, req.(*RejectMatchRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchRequestService_GetMatchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchRequestServiceServer).GetMatchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchRequestService_GetMatchRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchRequestServiceServer).GetMatchRequest(ctx, req.(*GetMatchRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchRequestService_CancelMatchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMatchRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchRequestServiceServer).CancelMatchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchRequestService_CancelMatchRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchRequestServiceServer).CancelMatchRequest(ctx, req.(*CancelMatchRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchRequestService_ServiceDesc is the grpc.ServiceDesc for MatchRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "match_request.MatchRequestService",
	HandlerType: (*MatchRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMatchRequest",
			Handler:    _MatchRequestService_CreateMatchRequest_Handler,
		},
		{
			MethodName: "GetUserMatchRequests",
			Handler:    _MatchRequestService_GetUserMatchRequests_Handler,
		},
		{
			MethodName: "AcceptMatchRequest",
			Handler:    _MatchRequestService_AcceptMatchRequest_Handler,
		},
		{
			MethodName: "RejectMatchRequest",
			Handler:    _MatchRequestService_RejectMatchRequest_Handler,
		},
		{
			MethodName: "GetMatchRequest",
			Handler:    _MatchRequestService_GetMatchRequest_Handler,
		},
		{
			MethodName: "CancelMatchRequest",
			Handler:    _MatchRequestService_CancelMatchRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "match_request/match_request.proto",
}
