// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: match_request/match_request.proto

package match_request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	CommonTopics  []string               `protobuf:"bytes,4,rep,name=common_topics,json=commonTopics,proto3" json:"common_topics,omitempty"`
	Similarity    float64                `protobuf:"fixed64,5,opt,name=similarity,proto3" json:"similarity,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_match_request_match_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MatchRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *MatchRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *MatchRequest) GetCommonTopics() []string {
	if x != nil {
		return x.CommonTopics
	}
	return nil
}

func (x *MatchRequest) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *MatchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatchRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MatchRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMatchRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	CommonTopics  []string               `protobuf:"bytes,3,rep,name=common_topics,json=commonTopics,proto3" json:"common_topics,omitempty"`
	Similarity    float64                `protobuf:"fixed64,4,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMatchRequestRequest) Reset() {
	*x = CreateMatchRequestRequest{}
	mi := &file_match_request_match_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMatchRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchRequestRequest) ProtoMessage() {}

func (x *CreateMatchRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateMatchRequestRequest) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMatchRequestRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *CreateMatchRequestRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *CreateMatchRequestRequest) GetCommonTopics() []string {
	if x != nil {
		return x.CommonTopics
	}
	return nil
}

func (x *CreateMatchRequestRequest) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

type CreateMatchRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchRequest  *MatchRequest          `protobuf:"bytes,1,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMatchRequestResponse) Reset() {
	*x = CreateMatchRequestResponse{}
	mi := &file_match_request_match_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMatchRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchRequestResponse) ProtoMessage() {}

func (x *CreateMatchRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateMatchRequestResponse) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMatchRequestResponse) GetMatchRequest() *MatchRequest {
	if x != nil {
		return x.MatchRequest
	}
	return nil
}

type GetUserMatchRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMatchRequestsRequest) Reset() {
	*x = GetUserMatchRequestsRequest{}
	mi := &file_match_request_match_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMatchRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMatchRequestsRequest) ProtoMessage() {}

func (x *GetUserMatchRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMatchRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetUserMatchRequestsRequest) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserMatchRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserMatchRequestsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserMatchRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchRequests []*MatchRequest        `protobuf:"bytes,1,rep,name=match_requests,json=matchRequests,proto3" json:"match_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMatchRequestsResponse) Reset() {
	*x = GetUserMatchRequestsResponse{}
	mi := &file_match_request_match_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMatchRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMatchRequestsResponse) ProtoMessage() {}

func (x *GetUserMatchRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMatchRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetUserMatchRequestsResponse) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserMatchRequestsResponse) GetMatchRequests() []*MatchRequest {
	if x != nil {
		return x.MatchRequests
	}
	return nil
}

type AcceptMatchRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMatchRequestRequest) Reset() {
	*x = AcceptMatchRequestRequest{}
	mi := &file_match_request_match_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMatchRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMatchRequestRequest) ProtoMessage() {}

func (x *AcceptMatchRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMatchRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptMatchRequestRequest) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptMatchRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AcceptMatchRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AcceptMatchRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchRequest  *MatchRequest          `protobuf:"bytes,1,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMatchRequestResponse) Reset() {
	*x = AcceptMatchRequestResponse{}
	mi := &file_match_request_match_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMatchRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMatchRequestResponse) ProtoMessage() {}

func (x *AcceptMatchRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMatchRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptMatchRequestResponse) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptMatchRequestResponse) GetMatchRequest() *MatchRequest {
	if x != nil {
		return x.MatchRequest
	}
	return nil
}

type RejectMatchRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectMatchRequestRequest) Reset() {
	*x = RejectMatchRequestRequest{}
	mi := &file_match_request_match_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectMatchRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectMatchRequestRequest) ProtoMessage() {}

func (x *RejectMatchRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectMatchRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectMatchRequestRequest) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{7}
}

func (x *RejectMatchRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RejectMatchRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RejectMatchRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchRequest  *MatchRequest          `protobuf:"bytes,1,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectMatchRequestResponse) Reset() {
	*x = RejectMatchRequestResponse{}
	mi := &file_match_request_match_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectMatchRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectMatchRequestResponse) ProtoMessage() {}

func (x *RejectMatchRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectMatchRequestResponse.ProtoReflect.Descriptor instead.
func (*RejectMatchRequestResponse) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{8}
}

func (x *RejectMatchRequestResponse) GetMatchRequest() *MatchRequest {
	if x != nil {
		return x.MatchRequest
	}
	return nil
}

type GetMatchRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchRequestRequest) Reset() {
	*x = GetMatchRequestRequest{}
	mi := &file_match_request_match_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequestRequest) ProtoMessage() {}

func (x *GetMatchRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequestRequest.ProtoReflect.Descriptor instead.
func (*GetMatchRequestRequest) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{9}
}

func (x *GetMatchRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetMatchRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchRequest  *MatchRequest          `protobuf:"bytes,1,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchRequestResponse) Reset() {
	*x = GetMatchRequestResponse{}
	mi := &file_match_request_match_request_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequestResponse) ProtoMessage() {}

func (x *GetMatchRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequestResponse.ProtoReflect.Descriptor instead.
func (*GetMatchRequestResponse) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{10}
}

func (x *GetMatchRequestResponse) GetMatchRequest() *MatchRequest {
	if x != nil {
		return x.MatchRequest
	}
	return nil
}

type CancelMatchRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchRequestRequest) Reset() {
	*x = CancelMatchRequestRequest{}
	mi := &file_match_request_match_request_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRequestRequest) ProtoMessage() {}

func (x *CancelMatchRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRequestRequest.ProtoReflect.Descriptor instead.
func (*CancelMatchRequestRequest) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{11}
}

func (x *CancelMatchRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelMatchRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelMatchRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchRequest  *MatchRequest          `protobuf:"bytes,1,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchRequestResponse) Reset() {
	*x = CancelMatchRequestResponse{}
	mi := &file_match_request_match_request_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRequestResponse) ProtoMessage() {}

func (x *CancelMatchRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_request_match_request_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRequestResponse.ProtoReflect.Descriptor instead.
func (*CancelMatchRequestResponse) Descriptor() ([]byte, []int) {
	return file_match_request_match_request_proto_rawDescGZIP(), []int{12}
}

func (x *CancelMatchRequestResponse) GetMatchRequest() *MatchRequest {
	if x != nil {
		return x.MatchRequest
	}
	return nil
}

var File_match_request_match_request_proto protoreflect.FileDescriptor

const file_match_request_match_request_proto_rawDesc = "" +
	"\n" +
	"!match_request/match_request.proto\x12\rmatch_request\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb1\x02\n" +
	"\fMatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\tR\btoUserId\x12#\n" +
	"\rcommon_topics\x18\x04 \x03(\tR\fcommonTopics\x12\x1e\n" +
	"\n" +
	"similarity\x18\x05 \x01(\x01R\n" +
	"similarity\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa0\x01\n" +
	"\x19CreateMatchRequestRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12#\n" +
	"\rcommon_topics\x18\x03 \x03(\tR\fcommonTopics\x12\x1e\n" +
	"\n" +
	"similarity\x18\x04 \x01(\x01R\n" +
	"similarity\"^\n" +
	"\x1aCreateMatchRequestResponse\x12@\n" +
	"\rmatch_request\x18\x01 \x01(\v2\x1b.match_request.MatchRequestR\fmatchRequest\"N\n" +
	"\x1bGetUserMatchRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"b\n" +
	"\x1cGetUserMatchRequestsResponse\x12B\n" +
	"\x0ematch_requests\x18\x01 \x03(\v2\x1b.match_request.MatchRequestR\rmatchRequests\"S\n" +
	"\x19AcceptMatchRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"^\n" +
	"\x1aAcceptMatchRequestResponse\x12@\n" +
	"\rmatch_request\x18\x01 \x01(\v2\x1b.match_request.MatchRequestR\fmatchRequest\"S\n" +
	"\x19RejectMatchRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"^\n" +
	"\x1aRejectMatchRequestResponse\x12@\n" +
	"\rmatch_request\x18\x01 \x01(\v2\x1b.match_request.MatchRequestR\fmatchRequest\"7\n" +
	"\x16GetMatchRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"[\n" +
	"\x17GetMatchRequestResponse\x12@\n" +
	"\rmatch_request\x18\x01 \x01(\v2\x1b.match_request.MatchRequestR\fmatchRequest\"S\n" +
	"\x19CancelMatchRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"^\n" +
	"\x1aCancelMatchRequestResponse\x12@\n" +
	"\rmatch_request\x18\x01 \x01(\v2\x1b.match_request.MatchRequestR\fmatchRequest2\x94\x05\n" +
	"\x13MatchRequestService\x12i\n" +
	"\x12CreateMatchRequest\x12(.match_request.CreateMatchRequestRequest\x1a).match_request.CreateMatchRequestResponse\x12o\n" +
	"\x14GetUserMatchRequests\x12*.match_request.GetUserMatchRequestsRequest\x1a+.match_request.GetUserMatchRequestsResponse\x12i\n" +
	"\x12AcceptMatchRequest\x12(.match_request.AcceptMatchRequestRequest\x1a).match_request.AcceptMatchRequestResponse\x12i\n" +
	"\x12RejectMatchRequest\x12(.match_request.RejectMatchRequestRequest\x1a).match_request.RejectMatchRequestResponse\x12`\n" +
	"\x0fGetMatchRequest\x12%.match_request.GetMatchRequestRequest\x1a&.match_request.GetMatchRequestResponse\x12i\n" +
	"\x12CancelMatchRequest\x12(.match_request.CancelMatchRequestRequest\x1a).match_request.CancelMatchRequestResponseB2Z0github.com/kegazani/metachat-proto/match_requestb\x06proto3"

var (
	file_match_request_match_request_proto_rawDescOnce sync.Once
	file_match_request_match_request_proto_rawDescData []byte
)

func file_match_request_match_request_proto_rawDescGZIP() []byte {
	file_match_request_match_request_proto_rawDescOnce.Do(func() {
		file_match_request_match_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_request_match_request_proto_rawDesc), len(file_match_request_match_request_proto_rawDesc)))
	})
	return file_match_request_match_request_proto_rawDescData
}

var file_match_request_match_request_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_match_request_match_request_proto_goTypes = []any{
	(*MatchRequest)(nil),                 // 0: match_request.MatchRequest
	(*CreateMatchRequestRequest)(nil),    // 1: match_request.CreateMatchRequestRequest
	(*CreateMatchRequestResponse)(nil),   // 2: match_request.CreateMatchRequestResponse
	(*GetUserMatchRequestsRequest)(nil),  // 3: match_request.GetUserMatchRequestsRequest
	(*GetUserMatchRequestsResponse)(nil), // 4: match_request.GetUserMatchRequestsResponse
	(*AcceptMatchRequestRequest)(nil),    // 5: match_request.AcceptMatchRequestRequest
	(*AcceptMatchRequestResponse)(nil),   // 6: match_request.AcceptMatchRequestResponse
	(*RejectMatchRequestRequest)(nil),    // 7: match_request.RejectMatchRequestRequest
	(*RejectMatchRequestResponse)(nil),   // 8: match_request.RejectMatchRequestResponse
	(*GetMatchRequestRequest)(nil),       // 9: match_request.GetMatchRequestRequest
	(*GetMatchRequestResponse)(nil),      // 10: match_request.GetMatchRequestResponse
	(*CancelMatchRequestRequest)(nil),    // 11: match_request.CancelMatchRequestRequest
	(*CancelMatchRequestResponse)(nil),   // 12: match_request.CancelMatchRequestResponse
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_match_request_match_request_proto_depIdxs = []int32{
	13, // 0: match_request.MatchRequest.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: match_request.MatchRequest.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: match_request.CreateMatchRequestResponse.match_request:type_name -> match_request.MatchRequest
	0,  // 3: match_request.GetUserMatchRequestsResponse.match_requests:type_name -> match_request.MatchRequest
	0,  // 4: match_request.AcceptMatchRequestResponse.match_request:type_name -> match_request.MatchRequest
	0,  // 5: match_request.RejectMatchRequestResponse.match_request:type_name -> match_request.MatchRequest
	0,  // 6: match_request.GetMatchRequestResponse.match_request:type_name -> match_request.MatchRequest
	0,  // 7: match_request.CancelMatchRequestResponse.match_request:type_name -> match_request.MatchRequest
	1,  // 8: match_request.MatchRequestService.CreateMatchRequest:input_type -> match_request.CreateMatchRequestRequest
	3,  // 9: match_request.MatchRequestService.GetUserMatchRequests:input_type -> match_request.GetUserMatchRequestsRequest
	5,  // 10: match_request.MatchRequestService.AcceptMatchRequest:input_type -> match_request.AcceptMatchRequestRequest
	7,  // 11: match_request.MatchRequestService.RejectMatchRequest:input_type -> match_request.RejectMatchRequestRequest
	9,  // 12: match_request.MatchRequestService.GetMatchRequest:input_type -> match_request.GetMatchRequestRequest
	11, // 13: match_request.MatchRequestService.CancelMatchRequest:input_type -> match_request.CancelMatchRequestRequest
	2,  // 14: match_request.MatchRequestService.CreateMatchRequest:output_type -> match_request.CreateMatchRequestResponse
	4,  // 15: match_request.MatchRequestService.GetUserMatchRequests:output_type -> match_request.GetUserMatchRequestsResponse
	6,  // 16: match_request.MatchRequestService.AcceptMatchRequest:output_type -> match_request.AcceptMatchRequestResponse
	8,  // 17: match_request.MatchRequestService.RejectMatchRequest:output_type -> match_request.RejectMatchRequestResponse
	10, // 18: match_request.MatchRequestService.GetMatchRequest:output_type -> match_request.GetMatchRequestResponse
	12, // 19: match_request.MatchRequestService.CancelMatchRequest:output_type -> match_request.CancelMatchRequestResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_match_request_match_request_proto_init() }
func file_match_request_match_request_proto_init() {
	if File_match_request_match_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_request_match_request_proto_rawDesc), len(file_match_request_match_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_match_request_match_request_proto_goTypes,
		DependencyIndexes: file_match_request_match_request_proto_depIdxs,
		MessageInfos:      file_match_request_match_request_proto_msgTypes,
	}.Build()
	File_match_request_match_request_proto = out.File
	file_match_request_match_request_proto_goTypes = nil
	file_match_request_match_request_proto_depIdxs = nil
}
