// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: matching/matching.proto

package matching

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User message
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_matching_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UserPortrait represents a user's emotional and psychological portrait
type UserPortrait struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	UserId            string                     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MoodProfile       map[string]float64         `protobuf:"bytes,2,rep,name=mood_profile,json=moodProfile,proto3" json:"mood_profile,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	PersonalityTraits map[string]float64         `protobuf:"bytes,3,rep,name=personality_traits,json=personalityTraits,proto3" json:"personality_traits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Interests         []string                   `protobuf:"bytes,4,rep,name=interests,proto3" json:"interests,omitempty"`
	Modalities        map[string]*structpb.Value `protobuf:"bytes,5,rep,name=modalities,proto3" json:"modalities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastUpdated       *timestamppb.Timestamp     `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserPortrait) Reset() {
	*x = UserPortrait{}
	mi := &file_matching_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPortrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPortrait) ProtoMessage() {}

func (x *UserPortrait) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPortrait.ProtoReflect.Descriptor instead.
func (*UserPortrait) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{1}
}

func (x *UserPortrait) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPortrait) GetMoodProfile() map[string]float64 {
	if x != nil {
		return x.MoodProfile
	}
	return nil
}

func (x *UserPortrait) GetPersonalityTraits() map[string]float64 {
	if x != nil {
		return x.PersonalityTraits
	}
	return nil
}

func (x *UserPortrait) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *UserPortrait) GetModalities() map[string]*structpb.Value {
	if x != nil {
		return x.Modalities
	}
	return nil
}

func (x *UserPortrait) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// UserMatch represents a match between two users
type UserMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId1       string                 `protobuf:"bytes,1,opt,name=user_id1,json=userId1,proto3" json:"user_id1,omitempty"`
	UserId2       string                 `protobuf:"bytes,2,opt,name=user_id2,json=userId2,proto3" json:"user_id2,omitempty"`
	Similarity    float64                `protobuf:"fixed64,3,opt,name=similarity,proto3" json:"similarity,omitempty"`
	CommonTags    []string               `protobuf:"bytes,4,rep,name=common_tags,json=commonTags,proto3" json:"common_tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMatch) Reset() {
	*x = UserMatch{}
	mi := &file_matching_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMatch) ProtoMessage() {}

func (x *UserMatch) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMatch.ProtoReflect.Descriptor instead.
func (*UserMatch) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{2}
}

func (x *UserMatch) GetUserId1() string {
	if x != nil {
		return x.UserId1
	}
	return ""
}

func (x *UserMatch) GetUserId2() string {
	if x != nil {
		return x.UserId2
	}
	return ""
}

func (x *UserMatch) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *UserMatch) GetCommonTags() []string {
	if x != nil {
		return x.CommonTags
	}
	return nil
}

func (x *UserMatch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request/Response messages
type FindSimilarUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarUsersRequest) Reset() {
	*x = FindSimilarUsersRequest{}
	mi := &file_matching_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarUsersRequest) ProtoMessage() {}

func (x *FindSimilarUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarUsersRequest.ProtoReflect.Descriptor instead.
func (*FindSimilarUsersRequest) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{3}
}

func (x *FindSimilarUsersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindSimilarUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FindSimilarUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*UserMatch           `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarUsersResponse) Reset() {
	*x = FindSimilarUsersResponse{}
	mi := &file_matching_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarUsersResponse) ProtoMessage() {}

func (x *FindSimilarUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarUsersResponse.ProtoReflect.Descriptor instead.
func (*FindSimilarUsersResponse) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{4}
}

func (x *FindSimilarUsersResponse) GetMatches() []*UserMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type CalculateUserSimilarityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId1       string                 `protobuf:"bytes,1,opt,name=user_id1,json=userId1,proto3" json:"user_id1,omitempty"`
	UserId2       string                 `protobuf:"bytes,2,opt,name=user_id2,json=userId2,proto3" json:"user_id2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateUserSimilarityRequest) Reset() {
	*x = CalculateUserSimilarityRequest{}
	mi := &file_matching_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateUserSimilarityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateUserSimilarityRequest) ProtoMessage() {}

func (x *CalculateUserSimilarityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateUserSimilarityRequest.ProtoReflect.Descriptor instead.
func (*CalculateUserSimilarityRequest) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateUserSimilarityRequest) GetUserId1() string {
	if x != nil {
		return x.UserId1
	}
	return ""
}

func (x *CalculateUserSimilarityRequest) GetUserId2() string {
	if x != nil {
		return x.UserId2
	}
	return ""
}

type CalculateUserSimilarityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Similarity    float64                `protobuf:"fixed64,1,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateUserSimilarityResponse) Reset() {
	*x = CalculateUserSimilarityResponse{}
	mi := &file_matching_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateUserSimilarityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateUserSimilarityResponse) ProtoMessage() {}

func (x *CalculateUserSimilarityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateUserSimilarityResponse.ProtoReflect.Descriptor instead.
func (*CalculateUserSimilarityResponse) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateUserSimilarityResponse) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

type SaveUserMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *UserMatch             `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserMatchRequest) Reset() {
	*x = SaveUserMatchRequest{}
	mi := &file_matching_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserMatchRequest) ProtoMessage() {}

func (x *SaveUserMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserMatchRequest.ProtoReflect.Descriptor instead.
func (*SaveUserMatchRequest) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{7}
}

func (x *SaveUserMatchRequest) GetMatch() *UserMatch {
	if x != nil {
		return x.Match
	}
	return nil
}

type SaveUserMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserMatchResponse) Reset() {
	*x = SaveUserMatchResponse{}
	mi := &file_matching_matching_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserMatchResponse) ProtoMessage() {}

func (x *SaveUserMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserMatchResponse.ProtoReflect.Descriptor instead.
func (*SaveUserMatchResponse) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{8}
}

func (x *SaveUserMatchResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetUserMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMatchesRequest) Reset() {
	*x = GetUserMatchesRequest{}
	mi := &file_matching_matching_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMatchesRequest) ProtoMessage() {}

func (x *GetUserMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMatchesRequest.ProtoReflect.Descriptor instead.
func (*GetUserMatchesRequest) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserMatchesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*UserMatch           `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMatchesResponse) Reset() {
	*x = GetUserMatchesResponse{}
	mi := &file_matching_matching_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMatchesResponse) ProtoMessage() {}

func (x *GetUserMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMatchesResponse.ProtoReflect.Descriptor instead.
func (*GetUserMatchesResponse) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserMatchesResponse) GetMatches() []*UserMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetUserPortraitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPortraitRequest) Reset() {
	*x = GetUserPortraitRequest{}
	mi := &file_matching_matching_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPortraitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPortraitRequest) ProtoMessage() {}

func (x *GetUserPortraitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPortraitRequest.ProtoReflect.Descriptor instead.
func (*GetUserPortraitRequest) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserPortraitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPortraitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Portrait      *UserPortrait          `protobuf:"bytes,1,opt,name=portrait,proto3" json:"portrait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPortraitResponse) Reset() {
	*x = GetUserPortraitResponse{}
	mi := &file_matching_matching_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPortraitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPortraitResponse) ProtoMessage() {}

func (x *GetUserPortraitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPortraitResponse.ProtoReflect.Descriptor instead.
func (*GetUserPortraitResponse) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserPortraitResponse) GetPortrait() *UserPortrait {
	if x != nil {
		return x.Portrait
	}
	return nil
}

type UpdateUserPortraitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Portrait      *UserPortrait          `protobuf:"bytes,2,opt,name=portrait,proto3" json:"portrait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPortraitRequest) Reset() {
	*x = UpdateUserPortraitRequest{}
	mi := &file_matching_matching_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPortraitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPortraitRequest) ProtoMessage() {}

func (x *UpdateUserPortraitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPortraitRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPortraitRequest) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserPortraitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPortraitRequest) GetPortrait() *UserPortrait {
	if x != nil {
		return x.Portrait
	}
	return nil
}

type UpdateUserPortraitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPortraitResponse) Reset() {
	*x = UpdateUserPortraitResponse{}
	mi := &file_matching_matching_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPortraitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPortraitResponse) ProtoMessage() {}

func (x *UpdateUserPortraitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPortraitResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPortraitResponse) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserPortraitResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetCommonTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId1       string                 `protobuf:"bytes,1,opt,name=user_id1,json=userId1,proto3" json:"user_id1,omitempty"`
	UserId2       string                 `protobuf:"bytes,2,opt,name=user_id2,json=userId2,proto3" json:"user_id2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommonTopicsRequest) Reset() {
	*x = GetCommonTopicsRequest{}
	mi := &file_matching_matching_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommonTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommonTopicsRequest) ProtoMessage() {}

func (x *GetCommonTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommonTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetCommonTopicsRequest) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{15}
}

func (x *GetCommonTopicsRequest) GetUserId1() string {
	if x != nil {
		return x.UserId1
	}
	return ""
}

func (x *GetCommonTopicsRequest) GetUserId2() string {
	if x != nil {
		return x.UserId2
	}
	return ""
}

type GetCommonTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonTopics  []string               `protobuf:"bytes,1,rep,name=common_topics,json=commonTopics,proto3" json:"common_topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommonTopicsResponse) Reset() {
	*x = GetCommonTopicsResponse{}
	mi := &file_matching_matching_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommonTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommonTopicsResponse) ProtoMessage() {}

func (x *GetCommonTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_matching_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommonTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetCommonTopicsResponse) Descriptor() ([]byte, []int) {
	return file_matching_matching_proto_rawDescGZIP(), []int{16}
}

func (x *GetCommonTopicsResponse) GetCommonTopics() []string {
	if x != nil {
		return x.CommonTopics
	}
	return nil
}

var File_matching_matching_proto protoreflect.FileDescriptor

const file_matching_matching_proto_rawDesc = "" +
	"\n" +
	"\x17matching/matching.proto\x12\bmatching\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb6\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd3\x04\n" +
	"\fUserPortrait\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12J\n" +
	"\fmood_profile\x18\x02 \x03(\v2'.matching.UserPortrait.MoodProfileEntryR\vmoodProfile\x12\\\n" +
	"\x12personality_traits\x18\x03 \x03(\v2-.matching.UserPortrait.PersonalityTraitsEntryR\x11personalityTraits\x12\x1c\n" +
	"\tinterests\x18\x04 \x03(\tR\tinterests\x12F\n" +
	"\n" +
	"modalities\x18\x05 \x03(\v2&.matching.UserPortrait.ModalitiesEntryR\n" +
	"modalities\x12=\n" +
	"\flast_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1a>\n" +
	"\x10MoodProfileEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aD\n" +
	"\x16PersonalityTraitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aU\n" +
	"\x0fModalitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xbd\x01\n" +
	"\tUserMatch\x12\x19\n" +
	"\buser_id1\x18\x01 \x01(\tR\auserId1\x12\x19\n" +
	"\buser_id2\x18\x02 \x01(\tR\auserId2\x12\x1e\n" +
	"\n" +
	"similarity\x18\x03 \x01(\x01R\n" +
	"similarity\x12\x1f\n" +
	"\vcommon_tags\x18\x04 \x03(\tR\n" +
	"commonTags\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"H\n" +
	"\x17FindSimilarUsersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"I\n" +
	"\x18FindSimilarUsersResponse\x12-\n" +
	"\amatches\x18\x01 \x03(\v2\x13.matching.UserMatchR\amatches\"V\n" +
	"\x1eCalculateUserSimilarityRequest\x12\x19\n" +
	"\buser_id1\x18\x01 \x01(\tR\auserId1\x12\x19\n" +
	"\buser_id2\x18\x02 \x01(\tR\auserId2\"A\n" +
	"\x1fCalculateUserSimilarityResponse\x12\x1e\n" +
	"\n" +
	"similarity\x18\x01 \x01(\x01R\n" +
	"similarity\"A\n" +
	"\x14SaveUserMatchRequest\x12)\n" +
	"\x05match\x18\x01 \x01(\v2\x13.matching.UserMatchR\x05match\"E\n" +
	"\x15SaveUserMatchResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"0\n" +
	"\x15GetUserMatchesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x16GetUserMatchesResponse\x12-\n" +
	"\amatches\x18\x01 \x03(\v2\x13.matching.UserMatchR\amatches\"1\n" +
	"\x16GetUserPortraitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x17GetUserPortraitResponse\x122\n" +
	"\bportrait\x18\x01 \x01(\v2\x16.matching.UserPortraitR\bportrait\"h\n" +
	"\x19UpdateUserPortraitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\bportrait\x18\x02 \x01(\v2\x16.matching.UserPortraitR\bportrait\"J\n" +
	"\x1aUpdateUserPortraitResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"N\n" +
	"\x16GetCommonTopicsRequest\x12\x19\n" +
	"\buser_id1\x18\x01 \x01(\tR\auserId1\x12\x19\n" +
	"\buser_id2\x18\x02 \x01(\tR\auserId2\">\n" +
	"\x17GetCommonTopicsResponse\x12#\n" +
	"\rcommon_topics\x18\x01 \x03(\tR\fcommonTopics2\x94\x05\n" +
	"\x0fMatchingService\x12Y\n" +
	"\x10FindSimilarUsers\x12!.matching.FindSimilarUsersRequest\x1a\".matching.FindSimilarUsersResponse\x12n\n" +
	"\x17CalculateUserSimilarity\x12(.matching.CalculateUserSimilarityRequest\x1a).matching.CalculateUserSimilarityResponse\x12P\n" +
	"\rSaveUserMatch\x12\x1e.matching.SaveUserMatchRequest\x1a\x1f.matching.SaveUserMatchResponse\x12S\n" +
	"\x0eGetUserMatches\x12\x1f.matching.GetUserMatchesRequest\x1a .matching.GetUserMatchesResponse\x12V\n" +
	"\x0fGetUserPortrait\x12 .matching.GetUserPortraitRequest\x1a!.matching.GetUserPortraitResponse\x12_\n" +
	"\x12UpdateUserPortrait\x12#.matching.UpdateUserPortraitRequest\x1a$.matching.UpdateUserPortraitResponse\x12V\n" +
	"\x0fGetCommonTopics\x12 .matching.GetCommonTopicsRequest\x1a!.matching.GetCommonTopicsResponseB-Z+github.com/kegazani/metachat-proto/matchingb\x06proto3"

var (
	file_matching_matching_proto_rawDescOnce sync.Once
	file_matching_matching_proto_rawDescData []byte
)

func file_matching_matching_proto_rawDescGZIP() []byte {
	file_matching_matching_proto_rawDescOnce.Do(func() {
		file_matching_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_matching_proto_rawDesc), len(file_matching_matching_proto_rawDesc)))
	})
	return file_matching_matching_proto_rawDescData
}

var file_matching_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_matching_matching_proto_goTypes = []any{
	(*User)(nil),                            // 0: matching.User
	(*UserPortrait)(nil),                    // 1: matching.UserPortrait
	(*UserMatch)(nil),                       // 2: matching.UserMatch
	(*FindSimilarUsersRequest)(nil),         // 3: matching.FindSimilarUsersRequest
	(*FindSimilarUsersResponse)(nil),        // 4: matching.FindSimilarUsersResponse
	(*CalculateUserSimilarityRequest)(nil),  // 5: matching.CalculateUserSimilarityRequest
	(*CalculateUserSimilarityResponse)(nil), // 6: matching.CalculateUserSimilarityResponse
	(*SaveUserMatchRequest)(nil),            // 7: matching.SaveUserMatchRequest
	(*SaveUserMatchResponse)(nil),           // 8: matching.SaveUserMatchResponse
	(*GetUserMatchesRequest)(nil),           // 9: matching.GetUserMatchesRequest
	(*GetUserMatchesResponse)(nil),          // 10: matching.GetUserMatchesResponse
	(*GetUserPortraitRequest)(nil),          // 11: matching.GetUserPortraitRequest
	(*GetUserPortraitResponse)(nil),         // 12: matching.GetUserPortraitResponse
	(*UpdateUserPortraitRequest)(nil),       // 13: matching.UpdateUserPortraitRequest
	(*UpdateUserPortraitResponse)(nil),      // 14: matching.UpdateUserPortraitResponse
	(*GetCommonTopicsRequest)(nil),          // 15: matching.GetCommonTopicsRequest
	(*GetCommonTopicsResponse)(nil),         // 16: matching.GetCommonTopicsResponse
	nil,                                     // 17: matching.UserPortrait.MoodProfileEntry
	nil,                                     // 18: matching.UserPortrait.PersonalityTraitsEntry
	nil,                                     // 19: matching.UserPortrait.ModalitiesEntry
	(*timestamppb.Timestamp)(nil),           // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 21: google.protobuf.Empty
	(*structpb.Value)(nil),                  // 22: google.protobuf.Value
}
var file_matching_matching_proto_depIdxs = []int32{
	20, // 0: matching.User.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: matching.User.updated_at:type_name -> google.protobuf.Timestamp
	17, // 2: matching.UserPortrait.mood_profile:type_name -> matching.UserPortrait.MoodProfileEntry
	18, // 3: matching.UserPortrait.personality_traits:type_name -> matching.UserPortrait.PersonalityTraitsEntry
	19, // 4: matching.UserPortrait.modalities:type_name -> matching.UserPortrait.ModalitiesEntry
	20, // 5: matching.UserPortrait.last_updated:type_name -> google.protobuf.Timestamp
	20, // 6: matching.UserMatch.created_at:type_name -> google.protobuf.Timestamp
	2,  // 7: matching.FindSimilarUsersResponse.matches:type_name -> matching.UserMatch
	2,  // 8: matching.SaveUserMatchRequest.match:type_name -> matching.UserMatch
	21, // 9: matching.SaveUserMatchResponse.empty:type_name -> google.protobuf.Empty
	2,  // 10: matching.GetUserMatchesResponse.matches:type_name -> matching.UserMatch
	1,  // 11: matching.GetUserPortraitResponse.portrait:type_name -> matching.UserPortrait
	1,  // 12: matching.UpdateUserPortraitRequest.portrait:type_name -> matching.UserPortrait
	21, // 13: matching.UpdateUserPortraitResponse.empty:type_name -> google.protobuf.Empty
	22, // 14: matching.UserPortrait.ModalitiesEntry.value:type_name -> google.protobuf.Value
	3,  // 15: matching.MatchingService.FindSimilarUsers:input_type -> matching.FindSimilarUsersRequest
	5,  // 16: matching.MatchingService.CalculateUserSimilarity:input_type -> matching.CalculateUserSimilarityRequest
	7,  // 17: matching.MatchingService.SaveUserMatch:input_type -> matching.SaveUserMatchRequest
	9,  // 18: matching.MatchingService.GetUserMatches:input_type -> matching.GetUserMatchesRequest
	11, // 19: matching.MatchingService.GetUserPortrait:input_type -> matching.GetUserPortraitRequest
	13, // 20: matching.MatchingService.UpdateUserPortrait:input_type -> matching.UpdateUserPortraitRequest
	15, // 21: matching.MatchingService.GetCommonTopics:input_type -> matching.GetCommonTopicsRequest
	4,  // 22: matching.MatchingService.FindSimilarUsers:output_type -> matching.FindSimilarUsersResponse
	6,  // 23: matching.MatchingService.CalculateUserSimilarity:output_type -> matching.CalculateUserSimilarityResponse
	8,  // 24: matching.MatchingService.SaveUserMatch:output_type -> matching.SaveUserMatchResponse
	10, // 25: matching.MatchingService.GetUserMatches:output_type -> matching.GetUserMatchesResponse
	12, // 26: matching.MatchingService.GetUserPortrait:output_type -> matching.GetUserPortraitResponse
	14, // 27: matching.MatchingService.UpdateUserPortrait:output_type -> matching.UpdateUserPortraitResponse
	16, // 28: matching.MatchingService.GetCommonTopics:output_type -> matching.GetCommonTopicsResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_matching_matching_proto_init() }
func file_matching_matching_proto_init() {
	if File_matching_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_matching_proto_rawDesc), len(file_matching_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_matching_proto_goTypes,
		DependencyIndexes: file_matching_matching_proto_depIdxs,
		MessageInfos:      file_matching_matching_proto_msgTypes,
	}.Build()
	File_matching_matching_proto = out.File
	file_matching_matching_proto_goTypes = nil
	file_matching_matching_proto_depIdxs = nil
}
