// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: matching/matching.proto

package matching

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingService_FindSimilarUsers_FullMethodName        = "/matching.MatchingService/FindSimilarUsers"
	MatchingService_CalculateUserSimilarity_FullMethodName = "/matching.MatchingService/CalculateUserSimilarity"
	MatchingService_SaveUserMatch_FullMethodName           = "/matching.MatchingService/SaveUserMatch"
	MatchingService_GetUserMatches_FullMethodName          = "/matching.MatchingService/GetUserMatches"
	MatchingService_GetUserPortrait_FullMethodName         = "/matching.MatchingService/GetUserPortrait"
	MatchingService_UpdateUserPortrait_FullMethodName      = "/matching.MatchingService/UpdateUserPortrait"
)

// MatchingServiceClient is the client API for MatchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchingService definition
type MatchingServiceClient interface {
	FindSimilarUsers(ctx context.Context, in *FindSimilarUsersRequest, opts ...grpc.CallOption) (*FindSimilarUsersResponse, error)
	CalculateUserSimilarity(ctx context.Context, in *CalculateUserSimilarityRequest, opts ...grpc.CallOption) (*CalculateUserSimilarityResponse, error)
	SaveUserMatch(ctx context.Context, in *SaveUserMatchRequest, opts ...grpc.CallOption) (*SaveUserMatchResponse, error)
	GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetUserMatchesResponse, error)
	GetUserPortrait(ctx context.Context, in *GetUserPortraitRequest, opts ...grpc.CallOption) (*GetUserPortraitResponse, error)
	UpdateUserPortrait(ctx context.Context, in *UpdateUserPortraitRequest, opts ...grpc.CallOption) (*UpdateUserPortraitResponse, error)
}

type matchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingServiceClient(cc grpc.ClientConnInterface) MatchingServiceClient {
	return &matchingServiceClient{cc}
}

func (c *matchingServiceClient) FindSimilarUsers(ctx context.Context, in *FindSimilarUsersRequest, opts ...grpc.CallOption) (*FindSimilarUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindSimilarUsersResponse)
	err := c.cc.Invoke(ctx, MatchingService_FindSimilarUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) CalculateUserSimilarity(ctx context.Context, in *CalculateUserSimilarityRequest, opts ...grpc.CallOption) (*CalculateUserSimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateUserSimilarityResponse)
	err := c.cc.Invoke(ctx, MatchingService_CalculateUserSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) SaveUserMatch(ctx context.Context, in *SaveUserMatchRequest, opts ...grpc.CallOption) (*SaveUserMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveUserMatchResponse)
	err := c.cc.Invoke(ctx, MatchingService_SaveUserMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetUserMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMatchesResponse)
	err := c.cc.Invoke(ctx, MatchingService_GetUserMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) GetUserPortrait(ctx context.Context, in *GetUserPortraitRequest, opts ...grpc.CallOption) (*GetUserPortraitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPortraitResponse)
	err := c.cc.Invoke(ctx, MatchingService_GetUserPortrait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingServiceClient) UpdateUserPortrait(ctx context.Context, in *UpdateUserPortraitRequest, opts ...grpc.CallOption) (*UpdateUserPortraitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserPortraitResponse)
	err := c.cc.Invoke(ctx, MatchingService_UpdateUserPortrait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingServiceServer is the server API for MatchingService service.
// All implementations must embed UnimplementedMatchingServiceServer
// for forward compatibility.
//
// MatchingService definition
type MatchingServiceServer interface {
	FindSimilarUsers(context.Context, *FindSimilarUsersRequest) (*FindSimilarUsersResponse, error)
	CalculateUserSimilarity(context.Context, *CalculateUserSimilarityRequest) (*CalculateUserSimilarityResponse, error)
	SaveUserMatch(context.Context, *SaveUserMatchRequest) (*SaveUserMatchResponse, error)
	GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetUserMatchesResponse, error)
	GetUserPortrait(context.Context, *GetUserPortraitRequest) (*GetUserPortraitResponse, error)
	UpdateUserPortrait(context.Context, *UpdateUserPortraitRequest) (*UpdateUserPortraitResponse, error)
	mustEmbedUnimplementedMatchingServiceServer()
}

// UnimplementedMatchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingServiceServer struct{}

func (UnimplementedMatchingServiceServer) FindSimilarUsers(context.Context, *FindSimilarUsersRequest) (*FindSimilarUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindSimilarUsers not implemented")
}
func (UnimplementedMatchingServiceServer) CalculateUserSimilarity(context.Context, *CalculateUserSimilarityRequest) (*CalculateUserSimilarityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateUserSimilarity not implemented")
}
func (UnimplementedMatchingServiceServer) SaveUserMatch(context.Context, *SaveUserMatchRequest) (*SaveUserMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveUserMatch not implemented")
}
func (UnimplementedMatchingServiceServer) GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetUserMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMatches not implemented")
}
func (UnimplementedMatchingServiceServer) GetUserPortrait(context.Context, *GetUserPortraitRequest) (*GetUserPortraitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPortrait not implemented")
}
func (UnimplementedMatchingServiceServer) UpdateUserPortrait(context.Context, *UpdateUserPortraitRequest) (*UpdateUserPortraitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserPortrait not implemented")
}
func (UnimplementedMatchingServiceServer) mustEmbedUnimplementedMatchingServiceServer() {}
func (UnimplementedMatchingServiceServer) testEmbeddedByValue()                         {}

// UnsafeMatchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingServiceServer will
// result in compilation errors.
type UnsafeMatchingServiceServer interface {
	mustEmbedUnimplementedMatchingServiceServer()
}

func RegisterMatchingServiceServer(s grpc.ServiceRegistrar, srv MatchingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingService_ServiceDesc, srv)
}

func _MatchingService_FindSimilarUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSimilarUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).FindSimilarUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_FindSimilarUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).FindSimilarUsers(ctx, req.(*FindSimilarUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_CalculateUserSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateUserSimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).CalculateUserSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_CalculateUserSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).CalculateUserSimilarity(ctx, req.(*CalculateUserSimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_SaveUserMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).SaveUserMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_SaveUserMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).SaveUserMatch(ctx, req.(*SaveUserMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetUserMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetUserMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetUserMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetUserMatches(ctx, req.(*GetUserMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_GetUserPortrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPortraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).GetUserPortrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_GetUserPortrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).GetUserPortrait(ctx, req.(*GetUserPortraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingService_UpdateUserPortrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPortraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingServiceServer).UpdateUserPortrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingService_UpdateUserPortrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingServiceServer).UpdateUserPortrait(ctx, req.(*UpdateUserPortraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingService_ServiceDesc is the grpc.ServiceDesc for MatchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matching.MatchingService",
	HandlerType: (*MatchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindSimilarUsers",
			Handler:    _MatchingService_FindSimilarUsers_Handler,
		},
		{
			MethodName: "CalculateUserSimilarity",
			Handler:    _MatchingService_CalculateUserSimilarity_Handler,
		},
		{
			MethodName: "SaveUserMatch",
			Handler:    _MatchingService_SaveUserMatch_Handler,
		},
		{
			MethodName: "GetUserMatches",
			Handler:    _MatchingService_GetUserMatches_Handler,
		},
		{
			MethodName: "GetUserPortrait",
			Handler:    _MatchingService_GetUserPortrait_Handler,
		},
		{
			MethodName: "UpdateUserPortrait",
			Handler:    _MatchingService_UpdateUserPortrait_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matching/matching.proto",
}
