// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: diary/diary.proto

package diary

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiaryService_CreateDiaryEntry_FullMethodName         = "/diary.DiaryService/CreateDiaryEntry"
	DiaryService_GetDiaryEntry_FullMethodName            = "/diary.DiaryService/GetDiaryEntry"
	DiaryService_UpdateDiaryEntry_FullMethodName         = "/diary.DiaryService/UpdateDiaryEntry"
	DiaryService_DeleteDiaryEntry_FullMethodName         = "/diary.DiaryService/DeleteDiaryEntry"
	DiaryService_StartDiarySession_FullMethodName        = "/diary.DiaryService/StartDiarySession"
	DiaryService_EndDiarySession_FullMethodName          = "/diary.DiaryService/EndDiarySession"
	DiaryService_GetDiarySession_FullMethodName          = "/diary.DiaryService/GetDiarySession"
	DiaryService_GetDiaryEntryReadModel_FullMethodName   = "/diary.DiaryService/GetDiaryEntryReadModel"
	DiaryService_GetDiarySessionReadModel_FullMethodName = "/diary.DiaryService/GetDiarySessionReadModel"
	DiaryService_ListDiaryEntries_FullMethodName         = "/diary.DiaryService/ListDiaryEntries"
	DiaryService_ListDiarySessions_FullMethodName        = "/diary.DiaryService/ListDiarySessions"
	DiaryService_GetDiaryEntriesByUser_FullMethodName    = "/diary.DiaryService/GetDiaryEntriesByUser"
	DiaryService_GetDiarySessionsByUser_FullMethodName   = "/diary.DiaryService/GetDiarySessionsByUser"
	DiaryService_GetDiaryAnalytics_FullMethodName        = "/diary.DiaryService/GetDiaryAnalytics"
)

// DiaryServiceClient is the client API for DiaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DiaryService definition
type DiaryServiceClient interface {
	CreateDiaryEntry(ctx context.Context, in *CreateDiaryEntryRequest, opts ...grpc.CallOption) (*CreateDiaryEntryResponse, error)
	GetDiaryEntry(ctx context.Context, in *GetDiaryEntryRequest, opts ...grpc.CallOption) (*GetDiaryEntryResponse, error)
	UpdateDiaryEntry(ctx context.Context, in *UpdateDiaryEntryRequest, opts ...grpc.CallOption) (*UpdateDiaryEntryResponse, error)
	DeleteDiaryEntry(ctx context.Context, in *DeleteDiaryEntryRequest, opts ...grpc.CallOption) (*DeleteDiaryEntryResponse, error)
	StartDiarySession(ctx context.Context, in *StartDiarySessionRequest, opts ...grpc.CallOption) (*StartDiarySessionResponse, error)
	EndDiarySession(ctx context.Context, in *EndDiarySessionRequest, opts ...grpc.CallOption) (*EndDiarySessionResponse, error)
	GetDiarySession(ctx context.Context, in *GetDiarySessionRequest, opts ...grpc.CallOption) (*GetDiarySessionResponse, error)
	GetDiaryEntryReadModel(ctx context.Context, in *GetDiaryEntryReadModelRequest, opts ...grpc.CallOption) (*GetDiaryEntryReadModelResponse, error)
	GetDiarySessionReadModel(ctx context.Context, in *GetDiarySessionReadModelRequest, opts ...grpc.CallOption) (*GetDiarySessionReadModelResponse, error)
	ListDiaryEntries(ctx context.Context, in *ListDiaryEntriesRequest, opts ...grpc.CallOption) (*ListDiaryEntriesResponse, error)
	ListDiarySessions(ctx context.Context, in *ListDiarySessionsRequest, opts ...grpc.CallOption) (*ListDiarySessionsResponse, error)
	GetDiaryEntriesByUser(ctx context.Context, in *GetDiaryEntriesByUserRequest, opts ...grpc.CallOption) (*GetDiaryEntriesByUserResponse, error)
	GetDiarySessionsByUser(ctx context.Context, in *GetDiarySessionsByUserRequest, opts ...grpc.CallOption) (*GetDiarySessionsByUserResponse, error)
	GetDiaryAnalytics(ctx context.Context, in *GetDiaryAnalyticsRequest, opts ...grpc.CallOption) (*GetDiaryAnalyticsResponse, error)
}

type diaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiaryServiceClient(cc grpc.ClientConnInterface) DiaryServiceClient {
	return &diaryServiceClient{cc}
}

func (c *diaryServiceClient) CreateDiaryEntry(ctx context.Context, in *CreateDiaryEntryRequest, opts ...grpc.CallOption) (*CreateDiaryEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiaryEntryResponse)
	err := c.cc.Invoke(ctx, DiaryService_CreateDiaryEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiaryEntry(ctx context.Context, in *GetDiaryEntryRequest, opts ...grpc.CallOption) (*GetDiaryEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiaryEntryResponse)
	err := c.cc.Invoke(ctx, DiaryService_GetDiaryEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) UpdateDiaryEntry(ctx context.Context, in *UpdateDiaryEntryRequest, opts ...grpc.CallOption) (*UpdateDiaryEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDiaryEntryResponse)
	err := c.cc.Invoke(ctx, DiaryService_UpdateDiaryEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) DeleteDiaryEntry(ctx context.Context, in *DeleteDiaryEntryRequest, opts ...grpc.CallOption) (*DeleteDiaryEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDiaryEntryResponse)
	err := c.cc.Invoke(ctx, DiaryService_DeleteDiaryEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) StartDiarySession(ctx context.Context, in *StartDiarySessionRequest, opts ...grpc.CallOption) (*StartDiarySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDiarySessionResponse)
	err := c.cc.Invoke(ctx, DiaryService_StartDiarySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) EndDiarySession(ctx context.Context, in *EndDiarySessionRequest, opts ...grpc.CallOption) (*EndDiarySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndDiarySessionResponse)
	err := c.cc.Invoke(ctx, DiaryService_EndDiarySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiarySession(ctx context.Context, in *GetDiarySessionRequest, opts ...grpc.CallOption) (*GetDiarySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiarySessionResponse)
	err := c.cc.Invoke(ctx, DiaryService_GetDiarySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiaryEntryReadModel(ctx context.Context, in *GetDiaryEntryReadModelRequest, opts ...grpc.CallOption) (*GetDiaryEntryReadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiaryEntryReadModelResponse)
	err := c.cc.Invoke(ctx, DiaryService_GetDiaryEntryReadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiarySessionReadModel(ctx context.Context, in *GetDiarySessionReadModelRequest, opts ...grpc.CallOption) (*GetDiarySessionReadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiarySessionReadModelResponse)
	err := c.cc.Invoke(ctx, DiaryService_GetDiarySessionReadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) ListDiaryEntries(ctx context.Context, in *ListDiaryEntriesRequest, opts ...grpc.CallOption) (*ListDiaryEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiaryEntriesResponse)
	err := c.cc.Invoke(ctx, DiaryService_ListDiaryEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) ListDiarySessions(ctx context.Context, in *ListDiarySessionsRequest, opts ...grpc.CallOption) (*ListDiarySessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiarySessionsResponse)
	err := c.cc.Invoke(ctx, DiaryService_ListDiarySessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiaryEntriesByUser(ctx context.Context, in *GetDiaryEntriesByUserRequest, opts ...grpc.CallOption) (*GetDiaryEntriesByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiaryEntriesByUserResponse)
	err := c.cc.Invoke(ctx, DiaryService_GetDiaryEntriesByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiarySessionsByUser(ctx context.Context, in *GetDiarySessionsByUserRequest, opts ...grpc.CallOption) (*GetDiarySessionsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiarySessionsByUserResponse)
	err := c.cc.Invoke(ctx, DiaryService_GetDiarySessionsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryServiceClient) GetDiaryAnalytics(ctx context.Context, in *GetDiaryAnalyticsRequest, opts ...grpc.CallOption) (*GetDiaryAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiaryAnalyticsResponse)
	err := c.cc.Invoke(ctx, DiaryService_GetDiaryAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiaryServiceServer is the server API for DiaryService service.
// All implementations must embed UnimplementedDiaryServiceServer
// for forward compatibility.
//
// DiaryService definition
type DiaryServiceServer interface {
	CreateDiaryEntry(context.Context, *CreateDiaryEntryRequest) (*CreateDiaryEntryResponse, error)
	GetDiaryEntry(context.Context, *GetDiaryEntryRequest) (*GetDiaryEntryResponse, error)
	UpdateDiaryEntry(context.Context, *UpdateDiaryEntryRequest) (*UpdateDiaryEntryResponse, error)
	DeleteDiaryEntry(context.Context, *DeleteDiaryEntryRequest) (*DeleteDiaryEntryResponse, error)
	StartDiarySession(context.Context, *StartDiarySessionRequest) (*StartDiarySessionResponse, error)
	EndDiarySession(context.Context, *EndDiarySessionRequest) (*EndDiarySessionResponse, error)
	GetDiarySession(context.Context, *GetDiarySessionRequest) (*GetDiarySessionResponse, error)
	GetDiaryEntryReadModel(context.Context, *GetDiaryEntryReadModelRequest) (*GetDiaryEntryReadModelResponse, error)
	GetDiarySessionReadModel(context.Context, *GetDiarySessionReadModelRequest) (*GetDiarySessionReadModelResponse, error)
	ListDiaryEntries(context.Context, *ListDiaryEntriesRequest) (*ListDiaryEntriesResponse, error)
	ListDiarySessions(context.Context, *ListDiarySessionsRequest) (*ListDiarySessionsResponse, error)
	GetDiaryEntriesByUser(context.Context, *GetDiaryEntriesByUserRequest) (*GetDiaryEntriesByUserResponse, error)
	GetDiarySessionsByUser(context.Context, *GetDiarySessionsByUserRequest) (*GetDiarySessionsByUserResponse, error)
	GetDiaryAnalytics(context.Context, *GetDiaryAnalyticsRequest) (*GetDiaryAnalyticsResponse, error)
	mustEmbedUnimplementedDiaryServiceServer()
}

// UnimplementedDiaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiaryServiceServer struct{}

func (UnimplementedDiaryServiceServer) CreateDiaryEntry(context.Context, *CreateDiaryEntryRequest) (*CreateDiaryEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDiaryEntry not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiaryEntry(context.Context, *GetDiaryEntryRequest) (*GetDiaryEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiaryEntry not implemented")
}
func (UnimplementedDiaryServiceServer) UpdateDiaryEntry(context.Context, *UpdateDiaryEntryRequest) (*UpdateDiaryEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDiaryEntry not implemented")
}
func (UnimplementedDiaryServiceServer) DeleteDiaryEntry(context.Context, *DeleteDiaryEntryRequest) (*DeleteDiaryEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDiaryEntry not implemented")
}
func (UnimplementedDiaryServiceServer) StartDiarySession(context.Context, *StartDiarySessionRequest) (*StartDiarySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDiarySession not implemented")
}
func (UnimplementedDiaryServiceServer) EndDiarySession(context.Context, *EndDiarySessionRequest) (*EndDiarySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndDiarySession not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiarySession(context.Context, *GetDiarySessionRequest) (*GetDiarySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiarySession not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiaryEntryReadModel(context.Context, *GetDiaryEntryReadModelRequest) (*GetDiaryEntryReadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiaryEntryReadModel not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiarySessionReadModel(context.Context, *GetDiarySessionReadModelRequest) (*GetDiarySessionReadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiarySessionReadModel not implemented")
}
func (UnimplementedDiaryServiceServer) ListDiaryEntries(context.Context, *ListDiaryEntriesRequest) (*ListDiaryEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiaryEntries not implemented")
}
func (UnimplementedDiaryServiceServer) ListDiarySessions(context.Context, *ListDiarySessionsRequest) (*ListDiarySessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiarySessions not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiaryEntriesByUser(context.Context, *GetDiaryEntriesByUserRequest) (*GetDiaryEntriesByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiaryEntriesByUser not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiarySessionsByUser(context.Context, *GetDiarySessionsByUserRequest) (*GetDiarySessionsByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiarySessionsByUser not implemented")
}
func (UnimplementedDiaryServiceServer) GetDiaryAnalytics(context.Context, *GetDiaryAnalyticsRequest) (*GetDiaryAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiaryAnalytics not implemented")
}
func (UnimplementedDiaryServiceServer) mustEmbedUnimplementedDiaryServiceServer() {}
func (UnimplementedDiaryServiceServer) testEmbeddedByValue()                      {}

// UnsafeDiaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiaryServiceServer will
// result in compilation errors.
type UnsafeDiaryServiceServer interface {
	mustEmbedUnimplementedDiaryServiceServer()
}

func RegisterDiaryServiceServer(s grpc.ServiceRegistrar, srv DiaryServiceServer) {
	// If the following call panics, it indicates UnimplementedDiaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiaryService_ServiceDesc, srv)
}

func _DiaryService_CreateDiaryEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiaryEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).CreateDiaryEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_CreateDiaryEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).CreateDiaryEntry(ctx, req.(*CreateDiaryEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiaryEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiaryEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiaryEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiaryEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiaryEntry(ctx, req.(*GetDiaryEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_UpdateDiaryEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDiaryEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).UpdateDiaryEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_UpdateDiaryEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).UpdateDiaryEntry(ctx, req.(*UpdateDiaryEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_DeleteDiaryEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiaryEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).DeleteDiaryEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_DeleteDiaryEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).DeleteDiaryEntry(ctx, req.(*DeleteDiaryEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_StartDiarySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDiarySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).StartDiarySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_StartDiarySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).StartDiarySession(ctx, req.(*StartDiarySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_EndDiarySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndDiarySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).EndDiarySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_EndDiarySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).EndDiarySession(ctx, req.(*EndDiarySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiarySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiarySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiarySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiarySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiarySession(ctx, req.(*GetDiarySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiaryEntryReadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiaryEntryReadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiaryEntryReadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiaryEntryReadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiaryEntryReadModel(ctx, req.(*GetDiaryEntryReadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiarySessionReadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiarySessionReadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiarySessionReadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiarySessionReadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiarySessionReadModel(ctx, req.(*GetDiarySessionReadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_ListDiaryEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiaryEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).ListDiaryEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_ListDiaryEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).ListDiaryEntries(ctx, req.(*ListDiaryEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_ListDiarySessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiarySessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).ListDiarySessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_ListDiarySessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).ListDiarySessions(ctx, req.(*ListDiarySessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiaryEntriesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiaryEntriesByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiaryEntriesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiaryEntriesByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiaryEntriesByUser(ctx, req.(*GetDiaryEntriesByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiarySessionsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiarySessionsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiarySessionsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiarySessionsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiarySessionsByUser(ctx, req.(*GetDiarySessionsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiaryService_GetDiaryAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiaryAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServiceServer).GetDiaryAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiaryService_GetDiaryAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServiceServer).GetDiaryAnalytics(ctx, req.(*GetDiaryAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiaryService_ServiceDesc is the grpc.ServiceDesc for DiaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diary.DiaryService",
	HandlerType: (*DiaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDiaryEntry",
			Handler:    _DiaryService_CreateDiaryEntry_Handler,
		},
		{
			MethodName: "GetDiaryEntry",
			Handler:    _DiaryService_GetDiaryEntry_Handler,
		},
		{
			MethodName: "UpdateDiaryEntry",
			Handler:    _DiaryService_UpdateDiaryEntry_Handler,
		},
		{
			MethodName: "DeleteDiaryEntry",
			Handler:    _DiaryService_DeleteDiaryEntry_Handler,
		},
		{
			MethodName: "StartDiarySession",
			Handler:    _DiaryService_StartDiarySession_Handler,
		},
		{
			MethodName: "EndDiarySession",
			Handler:    _DiaryService_EndDiarySession_Handler,
		},
		{
			MethodName: "GetDiarySession",
			Handler:    _DiaryService_GetDiarySession_Handler,
		},
		{
			MethodName: "GetDiaryEntryReadModel",
			Handler:    _DiaryService_GetDiaryEntryReadModel_Handler,
		},
		{
			MethodName: "GetDiarySessionReadModel",
			Handler:    _DiaryService_GetDiarySessionReadModel_Handler,
		},
		{
			MethodName: "ListDiaryEntries",
			Handler:    _DiaryService_ListDiaryEntries_Handler,
		},
		{
			MethodName: "ListDiarySessions",
			Handler:    _DiaryService_ListDiarySessions_Handler,
		},
		{
			MethodName: "GetDiaryEntriesByUser",
			Handler:    _DiaryService_GetDiaryEntriesByUser_Handler,
		},
		{
			MethodName: "GetDiarySessionsByUser",
			Handler:    _DiaryService_GetDiarySessionsByUser_Handler,
		},
		{
			MethodName: "GetDiaryAnalytics",
			Handler:    _DiaryService_GetDiaryAnalytics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diary/diary.proto",
}
