// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: diary/diary.proto

package diary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiaryEntry message
type DiaryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	TokenCount    int32                  `protobuf:"varint,5,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiaryEntry) Reset() {
	*x = DiaryEntry{}
	mi := &file_diary_diary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryEntry) ProtoMessage() {}

func (x *DiaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryEntry.ProtoReflect.Descriptor instead.
func (*DiaryEntry) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{0}
}

func (x *DiaryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiaryEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiaryEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiaryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DiaryEntry) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *DiaryEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DiaryEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DiaryEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DiaryEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DiarySession message
type DiarySession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	EntryCount    int32                  `protobuf:"varint,8,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiarySession) Reset() {
	*x = DiarySession{}
	mi := &file_diary_diary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiarySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiarySession) ProtoMessage() {}

func (x *DiarySession) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiarySession.ProtoReflect.Descriptor instead.
func (*DiarySession) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{1}
}

func (x *DiarySession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiarySession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiarySession) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiarySession) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DiarySession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DiarySession) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *DiarySession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiarySession) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

// DiaryEntryReadModel message
type DiaryEntryReadModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	TokenCount    int32                  `protobuf:"varint,5,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiaryEntryReadModel) Reset() {
	*x = DiaryEntryReadModel{}
	mi := &file_diary_diary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiaryEntryReadModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryEntryReadModel) ProtoMessage() {}

func (x *DiaryEntryReadModel) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryEntryReadModel.ProtoReflect.Descriptor instead.
func (*DiaryEntryReadModel) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{2}
}

func (x *DiaryEntryReadModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiaryEntryReadModel) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiaryEntryReadModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiaryEntryReadModel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DiaryEntryReadModel) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *DiaryEntryReadModel) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DiaryEntryReadModel) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DiaryEntryReadModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DiaryEntryReadModel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DiarySessionReadModel message
type DiarySessionReadModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	EntryCount    int32                  `protobuf:"varint,8,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiarySessionReadModel) Reset() {
	*x = DiarySessionReadModel{}
	mi := &file_diary_diary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiarySessionReadModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiarySessionReadModel) ProtoMessage() {}

func (x *DiarySessionReadModel) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiarySessionReadModel.ProtoReflect.Descriptor instead.
func (*DiarySessionReadModel) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{3}
}

func (x *DiarySessionReadModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiarySessionReadModel) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiarySessionReadModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiarySessionReadModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DiarySessionReadModel) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DiarySessionReadModel) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *DiarySessionReadModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiarySessionReadModel) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *DiarySessionReadModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DiarySessionReadModel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DiaryAnalytics message
type DiaryAnalytics struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries             int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	TotalSessions            int64                  `protobuf:"varint,2,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	ActiveUsers              int64                  `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	AverageEntriesPerSession float64                `protobuf:"fixed64,4,opt,name=average_entries_per_session,json=averageEntriesPerSession,proto3" json:"average_entries_per_session,omitempty"`
	AverageSessionsPerUser   float64                `protobuf:"fixed64,5,opt,name=average_sessions_per_user,json=averageSessionsPerUser,proto3" json:"average_sessions_per_user,omitempty"`
	LastUpdated              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DiaryAnalytics) Reset() {
	*x = DiaryAnalytics{}
	mi := &file_diary_diary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiaryAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryAnalytics) ProtoMessage() {}

func (x *DiaryAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryAnalytics.ProtoReflect.Descriptor instead.
func (*DiaryAnalytics) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{4}
}

func (x *DiaryAnalytics) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *DiaryAnalytics) GetTotalSessions() int64 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *DiaryAnalytics) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *DiaryAnalytics) GetAverageEntriesPerSession() float64 {
	if x != nil {
		return x.AverageEntriesPerSession
	}
	return 0
}

func (x *DiaryAnalytics) GetAverageSessionsPerUser() float64 {
	if x != nil {
		return x.AverageSessionsPerUser
	}
	return 0
}

func (x *DiaryAnalytics) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// Request/Response messages
type CreateDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TokenCount    int32                  `protobuf:"varint,4,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiaryEntryRequest) Reset() {
	*x = CreateDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiaryEntryRequest) ProtoMessage() {}

func (x *CreateDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDiaryEntryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateDiaryEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDiaryEntryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDiaryEntryRequest) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *CreateDiaryEntryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateDiaryEntryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DiaryEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiaryEntryResponse) Reset() {
	*x = CreateDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiaryEntryResponse) ProtoMessage() {}

func (x *CreateDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDiaryEntryResponse) GetEntry() *DiaryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntryRequest) Reset() {
	*x = GetDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntryRequest) ProtoMessage() {}

func (x *GetDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{7}
}

func (x *GetDiaryEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DiaryEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntryResponse) Reset() {
	*x = GetDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntryResponse) ProtoMessage() {}

func (x *GetDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{8}
}

func (x *GetDiaryEntryResponse) GetEntry() *DiaryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type UpdateDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TokenCount    int32                  `protobuf:"varint,4,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiaryEntryRequest) Reset() {
	*x = UpdateDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiaryEntryRequest) ProtoMessage() {}

func (x *UpdateDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDiaryEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDiaryEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDiaryEntryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateDiaryEntryRequest) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *UpdateDiaryEntryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateDiaryEntryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DiaryEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiaryEntryResponse) Reset() {
	*x = UpdateDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiaryEntryResponse) ProtoMessage() {}

func (x *UpdateDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*UpdateDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDiaryEntryResponse) GetEntry() *DiaryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type DeleteDiaryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiaryEntryRequest) Reset() {
	*x = DeleteDiaryEntryRequest{}
	mi := &file_diary_diary_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiaryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiaryEntryRequest) ProtoMessage() {}

func (x *DeleteDiaryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiaryEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiaryEntryRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDiaryEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDiaryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiaryEntryResponse) Reset() {
	*x = DeleteDiaryEntryResponse{}
	mi := &file_diary_diary_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiaryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiaryEntryResponse) ProtoMessage() {}

func (x *DeleteDiaryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiaryEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteDiaryEntryResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDiaryEntryResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type StartDiarySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDiarySessionRequest) Reset() {
	*x = StartDiarySessionRequest{}
	mi := &file_diary_diary_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDiarySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDiarySessionRequest) ProtoMessage() {}

func (x *StartDiarySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDiarySessionRequest.ProtoReflect.Descriptor instead.
func (*StartDiarySessionRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{13}
}

func (x *StartDiarySessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartDiarySessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartDiarySessionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StartDiarySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *DiarySession          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDiarySessionResponse) Reset() {
	*x = StartDiarySessionResponse{}
	mi := &file_diary_diary_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDiarySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDiarySessionResponse) ProtoMessage() {}

func (x *StartDiarySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDiarySessionResponse.ProtoReflect.Descriptor instead.
func (*StartDiarySessionResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{14}
}

func (x *StartDiarySessionResponse) GetSession() *DiarySession {
	if x != nil {
		return x.Session
	}
	return nil
}

type EndDiarySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndDiarySessionRequest) Reset() {
	*x = EndDiarySessionRequest{}
	mi := &file_diary_diary_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndDiarySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndDiarySessionRequest) ProtoMessage() {}

func (x *EndDiarySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndDiarySessionRequest.ProtoReflect.Descriptor instead.
func (*EndDiarySessionRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{15}
}

func (x *EndDiarySessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EndDiarySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *DiarySession          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndDiarySessionResponse) Reset() {
	*x = EndDiarySessionResponse{}
	mi := &file_diary_diary_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndDiarySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndDiarySessionResponse) ProtoMessage() {}

func (x *EndDiarySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndDiarySessionResponse.ProtoReflect.Descriptor instead.
func (*EndDiarySessionResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{16}
}

func (x *EndDiarySessionResponse) GetSession() *DiarySession {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetDiarySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiarySessionRequest) Reset() {
	*x = GetDiarySessionRequest{}
	mi := &file_diary_diary_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiarySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiarySessionRequest) ProtoMessage() {}

func (x *GetDiarySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiarySessionRequest.ProtoReflect.Descriptor instead.
func (*GetDiarySessionRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{17}
}

func (x *GetDiarySessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiarySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *DiarySession          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiarySessionResponse) Reset() {
	*x = GetDiarySessionResponse{}
	mi := &file_diary_diary_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiarySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiarySessionResponse) ProtoMessage() {}

func (x *GetDiarySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiarySessionResponse.ProtoReflect.Descriptor instead.
func (*GetDiarySessionResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{18}
}

func (x *GetDiarySessionResponse) GetSession() *DiarySession {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetDiaryEntryReadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntryReadModelRequest) Reset() {
	*x = GetDiaryEntryReadModelRequest{}
	mi := &file_diary_diary_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntryReadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntryReadModelRequest) ProtoMessage() {}

func (x *GetDiaryEntryReadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntryReadModelRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryEntryReadModelRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{19}
}

func (x *GetDiaryEntryReadModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiaryEntryReadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DiaryEntryReadModel   `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntryReadModelResponse) Reset() {
	*x = GetDiaryEntryReadModelResponse{}
	mi := &file_diary_diary_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntryReadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntryReadModelResponse) ProtoMessage() {}

func (x *GetDiaryEntryReadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntryReadModelResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryEntryReadModelResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{20}
}

func (x *GetDiaryEntryReadModelResponse) GetEntry() *DiaryEntryReadModel {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetDiarySessionReadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiarySessionReadModelRequest) Reset() {
	*x = GetDiarySessionReadModelRequest{}
	mi := &file_diary_diary_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiarySessionReadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiarySessionReadModelRequest) ProtoMessage() {}

func (x *GetDiarySessionReadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiarySessionReadModelRequest.ProtoReflect.Descriptor instead.
func (*GetDiarySessionReadModelRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{21}
}

func (x *GetDiarySessionReadModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiarySessionReadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *DiarySessionReadModel `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiarySessionReadModelResponse) Reset() {
	*x = GetDiarySessionReadModelResponse{}
	mi := &file_diary_diary_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiarySessionReadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiarySessionReadModelResponse) ProtoMessage() {}

func (x *GetDiarySessionReadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiarySessionReadModelResponse.ProtoReflect.Descriptor instead.
func (*GetDiarySessionReadModelResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{22}
}

func (x *GetDiarySessionReadModelResponse) GetSession() *DiarySessionReadModel {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListDiaryEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiaryEntriesRequest) Reset() {
	*x = ListDiaryEntriesRequest{}
	mi := &file_diary_diary_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiaryEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiaryEntriesRequest) ProtoMessage() {}

func (x *ListDiaryEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiaryEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListDiaryEntriesRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{23}
}

func (x *ListDiaryEntriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDiaryEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDiaryEntriesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListDiaryEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DiaryEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiaryEntriesResponse) Reset() {
	*x = ListDiaryEntriesResponse{}
	mi := &file_diary_diary_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiaryEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiaryEntriesResponse) ProtoMessage() {}

func (x *ListDiaryEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiaryEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListDiaryEntriesResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{24}
}

func (x *ListDiaryEntriesResponse) GetEntries() []*DiaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDiaryEntriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDiaryEntriesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDiaryEntriesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDiarySessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiarySessionsRequest) Reset() {
	*x = ListDiarySessionsRequest{}
	mi := &file_diary_diary_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiarySessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiarySessionsRequest) ProtoMessage() {}

func (x *ListDiarySessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiarySessionsRequest.ProtoReflect.Descriptor instead.
func (*ListDiarySessionsRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{25}
}

func (x *ListDiarySessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDiarySessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDiarySessionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListDiarySessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*DiarySession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiarySessionsResponse) Reset() {
	*x = ListDiarySessionsResponse{}
	mi := &file_diary_diary_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiarySessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiarySessionsResponse) ProtoMessage() {}

func (x *ListDiarySessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiarySessionsResponse.ProtoReflect.Descriptor instead.
func (*ListDiarySessionsResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{26}
}

func (x *ListDiarySessionsResponse) GetSessions() []*DiarySession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListDiarySessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDiarySessionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDiarySessionsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDiaryEntriesByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntriesByUserRequest) Reset() {
	*x = GetDiaryEntriesByUserRequest{}
	mi := &file_diary_diary_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntriesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntriesByUserRequest) ProtoMessage() {}

func (x *GetDiaryEntriesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntriesByUserRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryEntriesByUserRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{27}
}

func (x *GetDiaryEntriesByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDiaryEntriesByUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDiaryEntriesByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDiaryEntriesByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DiaryEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryEntriesByUserResponse) Reset() {
	*x = GetDiaryEntriesByUserResponse{}
	mi := &file_diary_diary_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryEntriesByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryEntriesByUserResponse) ProtoMessage() {}

func (x *GetDiaryEntriesByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryEntriesByUserResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryEntriesByUserResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{28}
}

func (x *GetDiaryEntriesByUserResponse) GetEntries() []*DiaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetDiaryEntriesByUserResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetDiaryEntriesByUserResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDiaryEntriesByUserResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDiarySessionsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiarySessionsByUserRequest) Reset() {
	*x = GetDiarySessionsByUserRequest{}
	mi := &file_diary_diary_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiarySessionsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiarySessionsByUserRequest) ProtoMessage() {}

func (x *GetDiarySessionsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiarySessionsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetDiarySessionsByUserRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{29}
}

func (x *GetDiarySessionsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDiarySessionsByUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDiarySessionsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDiarySessionsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*DiarySession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiarySessionsByUserResponse) Reset() {
	*x = GetDiarySessionsByUserResponse{}
	mi := &file_diary_diary_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiarySessionsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiarySessionsByUserResponse) ProtoMessage() {}

func (x *GetDiarySessionsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiarySessionsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetDiarySessionsByUserResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{30}
}

func (x *GetDiarySessionsByUserResponse) GetSessions() []*DiarySession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *GetDiarySessionsByUserResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetDiarySessionsByUserResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDiarySessionsByUserResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDiaryAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryAnalyticsRequest) Reset() {
	*x = GetDiaryAnalyticsRequest{}
	mi := &file_diary_diary_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryAnalyticsRequest) ProtoMessage() {}

func (x *GetDiaryAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetDiaryAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{31}
}

func (x *GetDiaryAnalyticsRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetDiaryAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analytics     *DiaryAnalytics        `protobuf:"bytes,1,opt,name=analytics,proto3" json:"analytics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiaryAnalyticsResponse) Reset() {
	*x = GetDiaryAnalyticsResponse{}
	mi := &file_diary_diary_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiaryAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiaryAnalyticsResponse) ProtoMessage() {}

func (x *GetDiaryAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diary_diary_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiaryAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetDiaryAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_diary_diary_proto_rawDescGZIP(), []int{32}
}

func (x *GetDiaryAnalyticsResponse) GetAnalytics() *DiaryAnalytics {
	if x != nil {
		return x.Analytics
	}
	return nil
}

var File_diary_diary_proto protoreflect.FileDescriptor

const file_diary_diary_proto_rawDesc = "" +
	"\n" +
	"\x11diary/diary.proto\x12\x05diary\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xaf\x02\n" +
	"\n" +
	"DiaryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vtoken_count\x18\x05 \x01(\x05R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x02\n" +
	"\fDiarySession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\ventry_count\x18\b \x01(\x05R\n" +
	"entryCount\"\xb8\x02\n" +
	"\x13DiaryEntryReadModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vtoken_count\x18\x05 \x01(\x05R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x99\x03\n" +
	"\x15DiarySessionReadModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\ventry_count\x18\b \x01(\x05R\n" +
	"entryCount\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb8\x02\n" +
	"\x0eDiaryAnalytics\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12%\n" +
	"\x0etotal_sessions\x18\x02 \x01(\x03R\rtotalSessions\x12!\n" +
	"\factive_users\x18\x03 \x01(\x03R\vactiveUsers\x12=\n" +
	"\x1baverage_entries_per_session\x18\x04 \x01(\x01R\x18averageEntriesPerSession\x129\n" +
	"\x19average_sessions_per_user\x18\x05 \x01(\x01R\x16averageSessionsPerUser\x12=\n" +
	"\flast_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xb6\x01\n" +
	"\x17CreateDiaryEntryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vtoken_count\x18\x04 \x01(\x05R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"C\n" +
	"\x18CreateDiaryEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.diary.DiaryEntryR\x05entry\"&\n" +
	"\x14GetDiaryEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x15GetDiaryEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.diary.DiaryEntryR\x05entry\"\xad\x01\n" +
	"\x17UpdateDiaryEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vtoken_count\x18\x04 \x01(\x05R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"C\n" +
	"\x18UpdateDiaryEntryResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.diary.DiaryEntryR\x05entry\")\n" +
	"\x17DeleteDiaryEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x18DeleteDiaryEntryResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"k\n" +
	"\x18StartDiarySessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"J\n" +
	"\x19StartDiarySessionResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.diary.DiarySessionR\asession\"(\n" +
	"\x16EndDiarySessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x17EndDiarySessionResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.diary.DiarySessionR\asession\"(\n" +
	"\x16GetDiarySessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x17GetDiarySessionResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.diary.DiarySessionR\asession\"/\n" +
	"\x1dGetDiaryEntryReadModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x1eGetDiaryEntryReadModelResponse\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.diary.DiaryEntryReadModelR\x05entry\"1\n" +
	"\x1fGetDiarySessionReadModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	" GetDiarySessionReadModelResponse\x126\n" +
	"\asession\x18\x01 \x01(\v2\x1c.diary.DiarySessionReadModelR\asession\"[\n" +
	"\x17ListDiaryEntriesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x87\x01\n" +
	"\x18ListDiaryEntriesResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.diary.DiaryEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\\\n" +
	"\x18ListDiarySessionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x8c\x01\n" +
	"\x19ListDiarySessionsResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.diary.DiarySessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"a\n" +
	"\x1cGetDiaryEntriesByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8c\x01\n" +
	"\x1dGetDiaryEntriesByUserResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.diary.DiaryEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"b\n" +
	"\x1dGetDiarySessionsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x91\x01\n" +
	"\x1eGetDiarySessionsByUserResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.diary.DiarySessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"H\n" +
	"\x18GetDiaryAnalyticsRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"P\n" +
	"\x19GetDiaryAnalyticsResponse\x123\n" +
	"\tanalytics\x18\x01 \x01(\v2\x15.diary.DiaryAnalyticsR\tanalytics2\xf9\t\n" +
	"\fDiaryService\x12S\n" +
	"\x10CreateDiaryEntry\x12\x1e.diary.CreateDiaryEntryRequest\x1a\x1f.diary.CreateDiaryEntryResponse\x12J\n" +
	"\rGetDiaryEntry\x12\x1b.diary.GetDiaryEntryRequest\x1a\x1c.diary.GetDiaryEntryResponse\x12S\n" +
	"\x10UpdateDiaryEntry\x12\x1e.diary.UpdateDiaryEntryRequest\x1a\x1f.diary.UpdateDiaryEntryResponse\x12S\n" +
	"\x10DeleteDiaryEntry\x12\x1e.diary.DeleteDiaryEntryRequest\x1a\x1f.diary.DeleteDiaryEntryResponse\x12V\n" +
	"\x11StartDiarySession\x12\x1f.diary.StartDiarySessionRequest\x1a .diary.StartDiarySessionResponse\x12P\n" +
	"\x0fEndDiarySession\x12\x1d.diary.EndDiarySessionRequest\x1a\x1e.diary.EndDiarySessionResponse\x12P\n" +
	"\x0fGetDiarySession\x12\x1d.diary.GetDiarySessionRequest\x1a\x1e.diary.GetDiarySessionResponse\x12e\n" +
	"\x16GetDiaryEntryReadModel\x12$.diary.GetDiaryEntryReadModelRequest\x1a%.diary.GetDiaryEntryReadModelResponse\x12k\n" +
	"\x18GetDiarySessionReadModel\x12&.diary.GetDiarySessionReadModelRequest\x1a'.diary.GetDiarySessionReadModelResponse\x12S\n" +
	"\x10ListDiaryEntries\x12\x1e.diary.ListDiaryEntriesRequest\x1a\x1f.diary.ListDiaryEntriesResponse\x12V\n" +
	"\x11ListDiarySessions\x12\x1f.diary.ListDiarySessionsRequest\x1a .diary.ListDiarySessionsResponse\x12b\n" +
	"\x15GetDiaryEntriesByUser\x12#.diary.GetDiaryEntriesByUserRequest\x1a$.diary.GetDiaryEntriesByUserResponse\x12e\n" +
	"\x16GetDiarySessionsByUser\x12$.diary.GetDiarySessionsByUserRequest\x1a%.diary.GetDiarySessionsByUserResponse\x12V\n" +
	"\x11GetDiaryAnalytics\x12\x1f.diary.GetDiaryAnalyticsRequest\x1a .diary.GetDiaryAnalyticsResponseB*Z(github.com/kegazani/metachat-proto/diaryb\x06proto3"

var (
	file_diary_diary_proto_rawDescOnce sync.Once
	file_diary_diary_proto_rawDescData []byte
)

func file_diary_diary_proto_rawDescGZIP() []byte {
	file_diary_diary_proto_rawDescOnce.Do(func() {
		file_diary_diary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diary_diary_proto_rawDesc), len(file_diary_diary_proto_rawDesc)))
	})
	return file_diary_diary_proto_rawDescData
}

var file_diary_diary_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_diary_diary_proto_goTypes = []any{
	(*DiaryEntry)(nil),                       // 0: diary.DiaryEntry
	(*DiarySession)(nil),                     // 1: diary.DiarySession
	(*DiaryEntryReadModel)(nil),              // 2: diary.DiaryEntryReadModel
	(*DiarySessionReadModel)(nil),            // 3: diary.DiarySessionReadModel
	(*DiaryAnalytics)(nil),                   // 4: diary.DiaryAnalytics
	(*CreateDiaryEntryRequest)(nil),          // 5: diary.CreateDiaryEntryRequest
	(*CreateDiaryEntryResponse)(nil),         // 6: diary.CreateDiaryEntryResponse
	(*GetDiaryEntryRequest)(nil),             // 7: diary.GetDiaryEntryRequest
	(*GetDiaryEntryResponse)(nil),            // 8: diary.GetDiaryEntryResponse
	(*UpdateDiaryEntryRequest)(nil),          // 9: diary.UpdateDiaryEntryRequest
	(*UpdateDiaryEntryResponse)(nil),         // 10: diary.UpdateDiaryEntryResponse
	(*DeleteDiaryEntryRequest)(nil),          // 11: diary.DeleteDiaryEntryRequest
	(*DeleteDiaryEntryResponse)(nil),         // 12: diary.DeleteDiaryEntryResponse
	(*StartDiarySessionRequest)(nil),         // 13: diary.StartDiarySessionRequest
	(*StartDiarySessionResponse)(nil),        // 14: diary.StartDiarySessionResponse
	(*EndDiarySessionRequest)(nil),           // 15: diary.EndDiarySessionRequest
	(*EndDiarySessionResponse)(nil),          // 16: diary.EndDiarySessionResponse
	(*GetDiarySessionRequest)(nil),           // 17: diary.GetDiarySessionRequest
	(*GetDiarySessionResponse)(nil),          // 18: diary.GetDiarySessionResponse
	(*GetDiaryEntryReadModelRequest)(nil),    // 19: diary.GetDiaryEntryReadModelRequest
	(*GetDiaryEntryReadModelResponse)(nil),   // 20: diary.GetDiaryEntryReadModelResponse
	(*GetDiarySessionReadModelRequest)(nil),  // 21: diary.GetDiarySessionReadModelRequest
	(*GetDiarySessionReadModelResponse)(nil), // 22: diary.GetDiarySessionReadModelResponse
	(*ListDiaryEntriesRequest)(nil),          // 23: diary.ListDiaryEntriesRequest
	(*ListDiaryEntriesResponse)(nil),         // 24: diary.ListDiaryEntriesResponse
	(*ListDiarySessionsRequest)(nil),         // 25: diary.ListDiarySessionsRequest
	(*ListDiarySessionsResponse)(nil),        // 26: diary.ListDiarySessionsResponse
	(*GetDiaryEntriesByUserRequest)(nil),     // 27: diary.GetDiaryEntriesByUserRequest
	(*GetDiaryEntriesByUserResponse)(nil),    // 28: diary.GetDiaryEntriesByUserResponse
	(*GetDiarySessionsByUserRequest)(nil),    // 29: diary.GetDiarySessionsByUserRequest
	(*GetDiarySessionsByUserResponse)(nil),   // 30: diary.GetDiarySessionsByUserResponse
	(*GetDiaryAnalyticsRequest)(nil),         // 31: diary.GetDiaryAnalyticsRequest
	(*GetDiaryAnalyticsResponse)(nil),        // 32: diary.GetDiaryAnalyticsResponse
	(*timestamppb.Timestamp)(nil),            // 33: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 34: google.protobuf.Empty
}
var file_diary_diary_proto_depIdxs = []int32{
	33, // 0: diary.DiaryEntry.created_at:type_name -> google.protobuf.Timestamp
	33, // 1: diary.DiaryEntry.updated_at:type_name -> google.protobuf.Timestamp
	33, // 2: diary.DiarySession.started_at:type_name -> google.protobuf.Timestamp
	33, // 3: diary.DiarySession.ended_at:type_name -> google.protobuf.Timestamp
	33, // 4: diary.DiaryEntryReadModel.created_at:type_name -> google.protobuf.Timestamp
	33, // 5: diary.DiaryEntryReadModel.updated_at:type_name -> google.protobuf.Timestamp
	33, // 6: diary.DiarySessionReadModel.started_at:type_name -> google.protobuf.Timestamp
	33, // 7: diary.DiarySessionReadModel.ended_at:type_name -> google.protobuf.Timestamp
	33, // 8: diary.DiarySessionReadModel.created_at:type_name -> google.protobuf.Timestamp
	33, // 9: diary.DiarySessionReadModel.updated_at:type_name -> google.protobuf.Timestamp
	33, // 10: diary.DiaryAnalytics.last_updated:type_name -> google.protobuf.Timestamp
	0,  // 11: diary.CreateDiaryEntryResponse.entry:type_name -> diary.DiaryEntry
	0,  // 12: diary.GetDiaryEntryResponse.entry:type_name -> diary.DiaryEntry
	0,  // 13: diary.UpdateDiaryEntryResponse.entry:type_name -> diary.DiaryEntry
	34, // 14: diary.DeleteDiaryEntryResponse.empty:type_name -> google.protobuf.Empty
	1,  // 15: diary.StartDiarySessionResponse.session:type_name -> diary.DiarySession
	1,  // 16: diary.EndDiarySessionResponse.session:type_name -> diary.DiarySession
	1,  // 17: diary.GetDiarySessionResponse.session:type_name -> diary.DiarySession
	2,  // 18: diary.GetDiaryEntryReadModelResponse.entry:type_name -> diary.DiaryEntryReadModel
	3,  // 19: diary.GetDiarySessionReadModelResponse.session:type_name -> diary.DiarySessionReadModel
	0,  // 20: diary.ListDiaryEntriesResponse.entries:type_name -> diary.DiaryEntry
	1,  // 21: diary.ListDiarySessionsResponse.sessions:type_name -> diary.DiarySession
	0,  // 22: diary.GetDiaryEntriesByUserResponse.entries:type_name -> diary.DiaryEntry
	1,  // 23: diary.GetDiarySessionsByUserResponse.sessions:type_name -> diary.DiarySession
	34, // 24: diary.GetDiaryAnalyticsRequest.empty:type_name -> google.protobuf.Empty
	4,  // 25: diary.GetDiaryAnalyticsResponse.analytics:type_name -> diary.DiaryAnalytics
	5,  // 26: diary.DiaryService.CreateDiaryEntry:input_type -> diary.CreateDiaryEntryRequest
	7,  // 27: diary.DiaryService.GetDiaryEntry:input_type -> diary.GetDiaryEntryRequest
	9,  // 28: diary.DiaryService.UpdateDiaryEntry:input_type -> diary.UpdateDiaryEntryRequest
	11, // 29: diary.DiaryService.DeleteDiaryEntry:input_type -> diary.DeleteDiaryEntryRequest
	13, // 30: diary.DiaryService.StartDiarySession:input_type -> diary.StartDiarySessionRequest
	15, // 31: diary.DiaryService.EndDiarySession:input_type -> diary.EndDiarySessionRequest
	17, // 32: diary.DiaryService.GetDiarySession:input_type -> diary.GetDiarySessionRequest
	19, // 33: diary.DiaryService.GetDiaryEntryReadModel:input_type -> diary.GetDiaryEntryReadModelRequest
	21, // 34: diary.DiaryService.GetDiarySessionReadModel:input_type -> diary.GetDiarySessionReadModelRequest
	23, // 35: diary.DiaryService.ListDiaryEntries:input_type -> diary.ListDiaryEntriesRequest
	25, // 36: diary.DiaryService.ListDiarySessions:input_type -> diary.ListDiarySessionsRequest
	27, // 37: diary.DiaryService.GetDiaryEntriesByUser:input_type -> diary.GetDiaryEntriesByUserRequest
	29, // 38: diary.DiaryService.GetDiarySessionsByUser:input_type -> diary.GetDiarySessionsByUserRequest
	31, // 39: diary.DiaryService.GetDiaryAnalytics:input_type -> diary.GetDiaryAnalyticsRequest
	6,  // 40: diary.DiaryService.CreateDiaryEntry:output_type -> diary.CreateDiaryEntryResponse
	8,  // 41: diary.DiaryService.GetDiaryEntry:output_type -> diary.GetDiaryEntryResponse
	10, // 42: diary.DiaryService.UpdateDiaryEntry:output_type -> diary.UpdateDiaryEntryResponse
	12, // 43: diary.DiaryService.DeleteDiaryEntry:output_type -> diary.DeleteDiaryEntryResponse
	14, // 44: diary.DiaryService.StartDiarySession:output_type -> diary.StartDiarySessionResponse
	16, // 45: diary.DiaryService.EndDiarySession:output_type -> diary.EndDiarySessionResponse
	18, // 46: diary.DiaryService.GetDiarySession:output_type -> diary.GetDiarySessionResponse
	20, // 47: diary.DiaryService.GetDiaryEntryReadModel:output_type -> diary.GetDiaryEntryReadModelResponse
	22, // 48: diary.DiaryService.GetDiarySessionReadModel:output_type -> diary.GetDiarySessionReadModelResponse
	24, // 49: diary.DiaryService.ListDiaryEntries:output_type -> diary.ListDiaryEntriesResponse
	26, // 50: diary.DiaryService.ListDiarySessions:output_type -> diary.ListDiarySessionsResponse
	28, // 51: diary.DiaryService.GetDiaryEntriesByUser:output_type -> diary.GetDiaryEntriesByUserResponse
	30, // 52: diary.DiaryService.GetDiarySessionsByUser:output_type -> diary.GetDiarySessionsByUserResponse
	32, // 53: diary.DiaryService.GetDiaryAnalytics:output_type -> diary.GetDiaryAnalyticsResponse
	40, // [40:54] is the sub-list for method output_type
	26, // [26:40] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_diary_diary_proto_init() }
func file_diary_diary_proto_init() {
	if File_diary_diary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diary_diary_proto_rawDesc), len(file_diary_diary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diary_diary_proto_goTypes,
		DependencyIndexes: file_diary_diary_proto_depIdxs,
		MessageInfos:      file_diary_diary_proto_msgTypes,
	}.Build()
	File_diary_diary_proto = out.File
	file_diary_diary_proto_goTypes = nil
	file_diary_diary_proto_depIdxs = nil
}
