// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: recommendation/recommendation.proto

package recommendation

import (
	matching "github.com/kegazani/metachat-proto/matching"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Content represents a piece of content in system
type Content struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                     `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g., "article", "video", "podcast"
	Tags          []string                   `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]*structpb.Value `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_recommendation_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Content) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Content) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Content) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Content) GetMetadata() map[string]*structpb.Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Content) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ContentRecommendation represents a content recommendation
type ContentRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // e.g., "similar_to_your_interests", "popular_in_your_community"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRecommendation) Reset() {
	*x = ContentRecommendation{}
	mi := &file_recommendation_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRecommendation) ProtoMessage() {}

func (x *ContentRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRecommendation.ProtoReflect.Descriptor instead.
func (*ContentRecommendation) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *ContentRecommendation) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ContentRecommendation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ContentRecommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Request/Response messages
type GetContentRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRecommendationsRequest) Reset() {
	*x = GetContentRecommendationsRequest{}
	mi := &file_recommendation_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRecommendationsRequest) ProtoMessage() {}

func (x *GetContentRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetContentRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetContentRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetContentRecommendationsResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Recommendations []*ContentRecommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetContentRecommendationsResponse) Reset() {
	*x = GetContentRecommendationsResponse{}
	mi := &file_recommendation_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRecommendationsResponse) ProtoMessage() {}

func (x *GetContentRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetContentRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentRecommendationsResponse) GetRecommendations() []*ContentRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type GetUserRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRecommendationsRequest) Reset() {
	*x = GetUserRecommendationsRequest{}
	mi := &file_recommendation_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRecommendationsRequest) ProtoMessage() {}

func (x *GetUserRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetUserRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*matching.UserMatch  `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRecommendationsResponse) Reset() {
	*x = GetUserRecommendationsResponse{}
	mi := &file_recommendation_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRecommendationsResponse) ProtoMessage() {}

func (x *GetUserRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetUserRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRecommendationsResponse) GetMatches() []*matching.UserMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetSimilarContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarContentRequest) Reset() {
	*x = GetSimilarContentRequest{}
	mi := &file_recommendation_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarContentRequest) ProtoMessage() {}

func (x *GetSimilarContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarContentRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarContentRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *GetSimilarContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetSimilarContentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSimilarContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []*Content             `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarContentResponse) Reset() {
	*x = GetSimilarContentResponse{}
	mi := &file_recommendation_recommendation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarContentResponse) ProtoMessage() {}

func (x *GetSimilarContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarContentResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarContentResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{7}
}

func (x *GetSimilarContentResponse) GetContent() []*Content {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_recommendation_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_recommendation_proto_rawDesc = "" +
	"\n" +
	"#recommendation/recommendation.proto\x12\x0erecommendation\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17matching/matching.proto\"\xcc\x02\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.recommendation.Content.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1aS\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"x\n" +
	"\x15ContentRecommendation\x121\n" +
	"\acontent\x18\x01 \x01(\v2\x17.recommendation.ContentR\acontent\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"Q\n" +
	" GetContentRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"t\n" +
	"!GetContentRecommendationsResponse\x12O\n" +
	"\x0frecommendations\x18\x01 \x03(\v2%.recommendation.ContentRecommendationR\x0frecommendations\"N\n" +
	"\x1dGetUserRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"O\n" +
	"\x1eGetUserRecommendationsResponse\x12-\n" +
	"\amatches\x18\x01 \x03(\v2\x13.matching.UserMatchR\amatches\"O\n" +
	"\x18GetSimilarContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"N\n" +
	"\x19GetSimilarContentResponse\x121\n" +
	"\acontent\x18\x01 \x03(\v2\x17.recommendation.ContentR\acontent2\xfd\x02\n" +
	"\x15RecommendationService\x12\x80\x01\n" +
	"\x19GetContentRecommendations\x120.recommendation.GetContentRecommendationsRequest\x1a1.recommendation.GetContentRecommendationsResponse\x12w\n" +
	"\x16GetUserRecommendations\x12-.recommendation.GetUserRecommendationsRequest\x1a..recommendation.GetUserRecommendationsResponse\x12h\n" +
	"\x11GetSimilarContent\x12(.recommendation.GetSimilarContentRequest\x1a).recommendation.GetSimilarContentResponseB3Z1github.com/kegazani/metachat-proto/recommendationb\x06proto3"

var (
	file_recommendation_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_recommendation_proto_rawDescData []byte
)

func file_recommendation_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_recommendation_proto_rawDesc), len(file_recommendation_recommendation_proto_rawDesc)))
	})
	return file_recommendation_recommendation_proto_rawDescData
}

var file_recommendation_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_recommendation_recommendation_proto_goTypes = []any{
	(*Content)(nil),                           // 0: recommendation.Content
	(*ContentRecommendation)(nil),             // 1: recommendation.ContentRecommendation
	(*GetContentRecommendationsRequest)(nil),  // 2: recommendation.GetContentRecommendationsRequest
	(*GetContentRecommendationsResponse)(nil), // 3: recommendation.GetContentRecommendationsResponse
	(*GetUserRecommendationsRequest)(nil),     // 4: recommendation.GetUserRecommendationsRequest
	(*GetUserRecommendationsResponse)(nil),    // 5: recommendation.GetUserRecommendationsResponse
	(*GetSimilarContentRequest)(nil),          // 6: recommendation.GetSimilarContentRequest
	(*GetSimilarContentResponse)(nil),         // 7: recommendation.GetSimilarContentResponse
	nil,                                       // 8: recommendation.Content.MetadataEntry
	(*timestamppb.Timestamp)(nil),             // 9: google.protobuf.Timestamp
	(*matching.UserMatch)(nil),                // 10: matching.UserMatch
	(*structpb.Value)(nil),                    // 11: google.protobuf.Value
}
var file_recommendation_recommendation_proto_depIdxs = []int32{
	8,  // 0: recommendation.Content.metadata:type_name -> recommendation.Content.MetadataEntry
	9,  // 1: recommendation.Content.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: recommendation.ContentRecommendation.content:type_name -> recommendation.Content
	1,  // 3: recommendation.GetContentRecommendationsResponse.recommendations:type_name -> recommendation.ContentRecommendation
	10, // 4: recommendation.GetUserRecommendationsResponse.matches:type_name -> matching.UserMatch
	0,  // 5: recommendation.GetSimilarContentResponse.content:type_name -> recommendation.Content
	11, // 6: recommendation.Content.MetadataEntry.value:type_name -> google.protobuf.Value
	2,  // 7: recommendation.RecommendationService.GetContentRecommendations:input_type -> recommendation.GetContentRecommendationsRequest
	4,  // 8: recommendation.RecommendationService.GetUserRecommendations:input_type -> recommendation.GetUserRecommendationsRequest
	6,  // 9: recommendation.RecommendationService.GetSimilarContent:input_type -> recommendation.GetSimilarContentRequest
	3,  // 10: recommendation.RecommendationService.GetContentRecommendations:output_type -> recommendation.GetContentRecommendationsResponse
	5,  // 11: recommendation.RecommendationService.GetUserRecommendations:output_type -> recommendation.GetUserRecommendationsResponse
	7,  // 12: recommendation.RecommendationService.GetSimilarContent:output_type -> recommendation.GetSimilarContentResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_recommendation_recommendation_proto_init() }
func file_recommendation_recommendation_proto_init() {
	if File_recommendation_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_recommendation_proto_rawDesc), len(file_recommendation_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_recommendation_proto_depIdxs,
		MessageInfos:      file_recommendation_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_recommendation_proto = out.File
	file_recommendation_recommendation_proto_goTypes = nil
	file_recommendation_recommendation_proto_depIdxs = nil
}
