// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: recommendation/recommendation.proto

package recommendation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommendationService_GetContentRecommendations_FullMethodName = "/recommendation.RecommendationService/GetContentRecommendations"
	RecommendationService_GetUserRecommendations_FullMethodName    = "/recommendation.RecommendationService/GetUserRecommendations"
	RecommendationService_GetSimilarContent_FullMethodName         = "/recommendation.RecommendationService/GetSimilarContent"
)

// RecommendationServiceClient is the client API for RecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecommendationService definition
type RecommendationServiceClient interface {
	GetContentRecommendations(ctx context.Context, in *GetContentRecommendationsRequest, opts ...grpc.CallOption) (*GetContentRecommendationsResponse, error)
	GetUserRecommendations(ctx context.Context, in *GetUserRecommendationsRequest, opts ...grpc.CallOption) (*GetUserRecommendationsResponse, error)
	GetSimilarContent(ctx context.Context, in *GetSimilarContentRequest, opts ...grpc.CallOption) (*GetSimilarContentResponse, error)
}

type recommendationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationServiceClient(cc grpc.ClientConnInterface) RecommendationServiceClient {
	return &recommendationServiceClient{cc}
}

func (c *recommendationServiceClient) GetContentRecommendations(ctx context.Context, in *GetContentRecommendationsRequest, opts ...grpc.CallOption) (*GetContentRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetContentRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetUserRecommendations(ctx context.Context, in *GetUserRecommendationsRequest, opts ...grpc.CallOption) (*GetUserRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetUserRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetSimilarContent(ctx context.Context, in *GetSimilarContentRequest, opts ...grpc.CallOption) (*GetSimilarContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimilarContentResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetSimilarContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServiceServer is the server API for RecommendationService service.
// All implementations must embed UnimplementedRecommendationServiceServer
// for forward compatibility.
//
// RecommendationService definition
type RecommendationServiceServer interface {
	GetContentRecommendations(context.Context, *GetContentRecommendationsRequest) (*GetContentRecommendationsResponse, error)
	GetUserRecommendations(context.Context, *GetUserRecommendationsRequest) (*GetUserRecommendationsResponse, error)
	GetSimilarContent(context.Context, *GetSimilarContentRequest) (*GetSimilarContentResponse, error)
	mustEmbedUnimplementedRecommendationServiceServer()
}

// UnimplementedRecommendationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendationServiceServer struct{}

func (UnimplementedRecommendationServiceServer) GetContentRecommendations(context.Context, *GetContentRecommendationsRequest) (*GetContentRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) GetUserRecommendations(context.Context, *GetUserRecommendationsRequest) (*GetUserRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) GetSimilarContent(context.Context, *GetSimilarContentRequest) (*GetSimilarContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimilarContent not implemented")
}
func (UnimplementedRecommendationServiceServer) mustEmbedUnimplementedRecommendationServiceServer() {}
func (UnimplementedRecommendationServiceServer) testEmbeddedByValue()                               {}

// UnsafeRecommendationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationServiceServer will
// result in compilation errors.
type UnsafeRecommendationServiceServer interface {
	mustEmbedUnimplementedRecommendationServiceServer()
}

func RegisterRecommendationServiceServer(s grpc.ServiceRegistrar, srv RecommendationServiceServer) {
	// If the following call panics, it indicates UnimplementedRecommendationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendationService_ServiceDesc, srv)
}

func _RecommendationService_GetContentRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetContentRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetContentRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetContentRecommendations(ctx, req.(*GetContentRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetUserRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetUserRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetUserRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetUserRecommendations(ctx, req.(*GetUserRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetSimilarContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimilarContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetSimilarContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetSimilarContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetSimilarContent(ctx, req.(*GetSimilarContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationService_ServiceDesc is the grpc.ServiceDesc for RecommendationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommendation.RecommendationService",
	HandlerType: (*RecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContentRecommendations",
			Handler:    _RecommendationService_GetContentRecommendations_Handler,
		},
		{
			MethodName: "GetUserRecommendations",
			Handler:    _RecommendationService_GetUserRecommendations_Handler,
		},
		{
			MethodName: "GetSimilarContent",
			Handler:    _RecommendationService_GetSimilarContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommendation/recommendation.proto",
}
