// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User message
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Archetype message
type Archetype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AssignedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Archetype) Reset() {
	*x = Archetype{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Archetype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Archetype) ProtoMessage() {}

func (x *Archetype) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Archetype.ProtoReflect.Descriptor instead.
func (*Archetype) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *Archetype) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Archetype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Archetype) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Archetype) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Archetype) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignedAt
	}
	return nil
}

// UserModality message
type UserModality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModality) Reset() {
	*x = UserModality{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModality) ProtoMessage() {}

func (x *UserModality) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModality.ProtoReflect.Descriptor instead.
func (*UserModality) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserModality) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserModality) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserModality) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserModality) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// UserReadModel message
type UserReadModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FullName      string                 `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReadModel) Reset() {
	*x = UserReadModel{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReadModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReadModel) ProtoMessage() {}

func (x *UserReadModel) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReadModel.ProtoReflect.Descriptor instead.
func (*UserReadModel) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserReadModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserReadModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserReadModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReadModel) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserReadModel) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserReadModel) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserReadModel) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserReadModel) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserReadModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserReadModel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UserArchetypeReadModel message
type UserArchetypeReadModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArchetypeId   string                 `protobuf:"bytes,2,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	ArchetypeName string                 `protobuf:"bytes,3,opt,name=archetype_name,json=archetypeName,proto3" json:"archetype_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AssignedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserArchetypeReadModel) Reset() {
	*x = UserArchetypeReadModel{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserArchetypeReadModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserArchetypeReadModel) ProtoMessage() {}

func (x *UserArchetypeReadModel) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserArchetypeReadModel.ProtoReflect.Descriptor instead.
func (*UserArchetypeReadModel) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserArchetypeReadModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserArchetypeReadModel) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

func (x *UserArchetypeReadModel) GetArchetypeName() string {
	if x != nil {
		return x.ArchetypeName
	}
	return ""
}

func (x *UserArchetypeReadModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserArchetypeReadModel) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *UserArchetypeReadModel) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignedAt
	}
	return nil
}

func (x *UserArchetypeReadModel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request/Response messages
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResponse) Reset() {
	*x = UpdateUserProfileResponse{}
	mi := &file_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResponse) ProtoMessage() {}

func (x *UpdateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AssignArchetypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArchetypeId   string                 `protobuf:"bytes,2,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	ArchetypeName string                 `protobuf:"bytes,3,opt,name=archetype_name,json=archetypeName,proto3" json:"archetype_name,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignArchetypeRequest) Reset() {
	*x = AssignArchetypeRequest{}
	mi := &file_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignArchetypeRequest) ProtoMessage() {}

func (x *AssignArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignArchetypeRequest.ProtoReflect.Descriptor instead.
func (*AssignArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *AssignArchetypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignArchetypeRequest) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

func (x *AssignArchetypeRequest) GetArchetypeName() string {
	if x != nil {
		return x.ArchetypeName
	}
	return ""
}

func (x *AssignArchetypeRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AssignArchetypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AssignArchetypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignArchetypeResponse) Reset() {
	*x = AssignArchetypeResponse{}
	mi := &file_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignArchetypeResponse) ProtoMessage() {}

func (x *AssignArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignArchetypeResponse.ProtoReflect.Descriptor instead.
func (*AssignArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *AssignArchetypeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateArchetypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArchetypeId   string                 `protobuf:"bytes,2,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	ArchetypeName string                 `protobuf:"bytes,3,opt,name=archetype_name,json=archetypeName,proto3" json:"archetype_name,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArchetypeRequest) Reset() {
	*x = UpdateArchetypeRequest{}
	mi := &file_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArchetypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArchetypeRequest) ProtoMessage() {}

func (x *UpdateArchetypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArchetypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateArchetypeRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateArchetypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArchetypeRequest) GetArchetypeId() string {
	if x != nil {
		return x.ArchetypeId
	}
	return ""
}

func (x *UpdateArchetypeRequest) GetArchetypeName() string {
	if x != nil {
		return x.ArchetypeName
	}
	return ""
}

func (x *UpdateArchetypeRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *UpdateArchetypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateArchetypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArchetypeResponse) Reset() {
	*x = UpdateArchetypeResponse{}
	mi := &file_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArchetypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArchetypeResponse) ProtoMessage() {}

func (x *UpdateArchetypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArchetypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateArchetypeResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateArchetypeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateModalitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Modalities    []*UserModality        `protobuf:"bytes,2,rep,name=modalities,proto3" json:"modalities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModalitiesRequest) Reset() {
	*x = UpdateModalitiesRequest{}
	mi := &file_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModalitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModalitiesRequest) ProtoMessage() {}

func (x *UpdateModalitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModalitiesRequest.ProtoReflect.Descriptor instead.
func (*UpdateModalitiesRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateModalitiesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModalitiesRequest) GetModalities() []*UserModality {
	if x != nil {
		return x.Modalities
	}
	return nil
}

type UpdateModalitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModalitiesResponse) Reset() {
	*x = UpdateModalitiesResponse{}
	mi := &file_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModalitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModalitiesResponse) ProtoMessage() {}

func (x *UpdateModalitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModalitiesResponse.ProtoReflect.Descriptor instead.
func (*UpdateModalitiesResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateModalitiesResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserReadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReadModelRequest) Reset() {
	*x = GetUserReadModelRequest{}
	mi := &file_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReadModelRequest) ProtoMessage() {}

func (x *GetUserReadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReadModelRequest.ProtoReflect.Descriptor instead.
func (*GetUserReadModelRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserReadModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserReadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserReadModel         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReadModelResponse) Reset() {
	*x = GetUserReadModelResponse{}
	mi := &file_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReadModelResponse) ProtoMessage() {}

func (x *GetUserReadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReadModelResponse.ProtoReflect.Descriptor instead.
func (*GetUserReadModelResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserReadModelResponse) GetUser() *UserReadModel {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserArchetypeReadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserArchetypeReadModelRequest) Reset() {
	*x = GetUserArchetypeReadModelRequest{}
	mi := &file_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserArchetypeReadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserArchetypeReadModelRequest) ProtoMessage() {}

func (x *GetUserArchetypeReadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserArchetypeReadModelRequest.ProtoReflect.Descriptor instead.
func (*GetUserArchetypeReadModelRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserArchetypeReadModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserArchetypeReadModelResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserArchetype *UserArchetypeReadModel `protobuf:"bytes,1,opt,name=user_archetype,json=userArchetype,proto3" json:"user_archetype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserArchetypeReadModelResponse) Reset() {
	*x = GetUserArchetypeReadModelResponse{}
	mi := &file_user_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserArchetypeReadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserArchetypeReadModelResponse) ProtoMessage() {}

func (x *GetUserArchetypeReadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserArchetypeReadModelResponse.ProtoReflect.Descriptor instead.
func (*GetUserArchetypeReadModelResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserArchetypeReadModelResponse) GetUserArchetype() *UserArchetypeReadModel {
	if x != nil {
		return x.UserArchetype
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{21}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{22}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{23}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{24}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{25}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{26}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProfileProgress struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TokensAnalyzed          int32                  `protobuf:"varint,1,opt,name=tokens_analyzed,json=tokensAnalyzed,proto3" json:"tokens_analyzed,omitempty"`
	TokensRequiredForFirst  int32                  `protobuf:"varint,2,opt,name=tokens_required_for_first,json=tokensRequiredForFirst,proto3" json:"tokens_required_for_first,omitempty"`
	TokensRequiredForRecalc int32                  `protobuf:"varint,3,opt,name=tokens_required_for_recalc,json=tokensRequiredForRecalc,proto3" json:"tokens_required_for_recalc,omitempty"`
	DaysSinceLastCalc       int32                  `protobuf:"varint,4,opt,name=days_since_last_calc,json=daysSinceLastCalc,proto3" json:"days_since_last_calc,omitempty"`
	DaysUntilRecalc         int32                  `protobuf:"varint,5,opt,name=days_until_recalc,json=daysUntilRecalc,proto3" json:"days_until_recalc,omitempty"`
	IsFirstCalculation      bool                   `protobuf:"varint,6,opt,name=is_first_calculation,json=isFirstCalculation,proto3" json:"is_first_calculation,omitempty"`
	ProgressPercentage      float64                `protobuf:"fixed64,7,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProfileProgress) Reset() {
	*x = ProfileProgress{}
	mi := &file_user_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileProgress) ProtoMessage() {}

func (x *ProfileProgress) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileProgress.ProtoReflect.Descriptor instead.
func (*ProfileProgress) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{27}
}

func (x *ProfileProgress) GetTokensAnalyzed() int32 {
	if x != nil {
		return x.TokensAnalyzed
	}
	return 0
}

func (x *ProfileProgress) GetTokensRequiredForFirst() int32 {
	if x != nil {
		return x.TokensRequiredForFirst
	}
	return 0
}

func (x *ProfileProgress) GetTokensRequiredForRecalc() int32 {
	if x != nil {
		return x.TokensRequiredForRecalc
	}
	return 0
}

func (x *ProfileProgress) GetDaysSinceLastCalc() int32 {
	if x != nil {
		return x.DaysSinceLastCalc
	}
	return 0
}

func (x *ProfileProgress) GetDaysUntilRecalc() int32 {
	if x != nil {
		return x.DaysUntilRecalc
	}
	return 0
}

func (x *ProfileProgress) GetIsFirstCalculation() bool {
	if x != nil {
		return x.IsFirstCalculation
	}
	return false
}

func (x *ProfileProgress) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

type UserStatistics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalDiaryEntries     int32                  `protobuf:"varint,1,opt,name=total_diary_entries,json=totalDiaryEntries,proto3" json:"total_diary_entries,omitempty"`
	TotalMoodAnalyses     int32                  `protobuf:"varint,2,opt,name=total_mood_analyses,json=totalMoodAnalyses,proto3" json:"total_mood_analyses,omitempty"`
	TotalTokens           int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	DominantEmotion       string                 `protobuf:"bytes,4,opt,name=dominant_emotion,json=dominantEmotion,proto3" json:"dominant_emotion,omitempty"`
	TopTopics             []string               `protobuf:"bytes,5,rep,name=top_topics,json=topTopics,proto3" json:"top_topics,omitempty"`
	ProfileCreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=profile_created_at,json=profileCreatedAt,proto3" json:"profile_created_at,omitempty"`
	LastPersonalityUpdate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_personality_update,json=lastPersonalityUpdate,proto3" json:"last_personality_update,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserStatistics) Reset() {
	*x = UserStatistics{}
	mi := &file_user_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatistics) ProtoMessage() {}

func (x *UserStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatistics.ProtoReflect.Descriptor instead.
func (*UserStatistics) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{28}
}

func (x *UserStatistics) GetTotalDiaryEntries() int32 {
	if x != nil {
		return x.TotalDiaryEntries
	}
	return 0
}

func (x *UserStatistics) GetTotalMoodAnalyses() int32 {
	if x != nil {
		return x.TotalMoodAnalyses
	}
	return 0
}

func (x *UserStatistics) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *UserStatistics) GetDominantEmotion() string {
	if x != nil {
		return x.DominantEmotion
	}
	return ""
}

func (x *UserStatistics) GetTopTopics() []string {
	if x != nil {
		return x.TopTopics
	}
	return nil
}

func (x *UserStatistics) GetProfileCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProfileCreatedAt
	}
	return nil
}

func (x *UserStatistics) GetLastPersonalityUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPersonalityUpdate
	}
	return nil
}

type GetUserProfileProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileProgressRequest) Reset() {
	*x = GetUserProfileProgressRequest{}
	mi := &file_user_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileProgressRequest) ProtoMessage() {}

func (x *GetUserProfileProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileProgressRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{29}
}

func (x *GetUserProfileProgressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserProfileProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *ProfileProgress       `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileProgressResponse) Reset() {
	*x = GetUserProfileProgressResponse{}
	mi := &file_user_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileProgressResponse) ProtoMessage() {}

func (x *GetUserProfileProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileProgressResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileProgressResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{30}
}

func (x *GetUserProfileProgressResponse) GetProgress() *ProfileProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type GetUserStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatisticsRequest) Reset() {
	*x = GetUserStatisticsRequest{}
	mi := &file_user_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatisticsRequest) ProtoMessage() {}

func (x *GetUserStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{31}
}

func (x *GetUserStatisticsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *UserStatistics        `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatisticsResponse) Reset() {
	*x = GetUserStatisticsResponse{}
	mi := &file_user_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatisticsResponse) ProtoMessage() {}

func (x *GetUserStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{32}
}

func (x *GetUserStatisticsResponse) GetStatistics() *UserStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc8\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\b \x01(\tR\x03bio\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xae\x01\n" +
	"\tArchetype\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12;\n" +
	"\vassigned_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\"j\n" +
	"\fUserModality\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xca\x02\n" +
	"\rUserReadModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1b\n" +
	"\tfull_name\x18\x06 \x01(\tR\bfullName\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\b \x01(\tR\x03bio\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x02\n" +
	"\x16UserArchetypeReadModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\farchetype_id\x18\x02 \x01(\tR\varchetypeId\x12%\n" +
	"\x0earchetype_name\x18\x03 \x01(\tR\rarchetypeName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12;\n" +
	"\vassigned_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa5\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x05 \x01(\tR\vdateOfBirth\"4\n" +
	"\x12CreateUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"\xb4\x01\n" +
	"\x18UpdateUserProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\";\n" +
	"\x19UpdateUserProfileResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"\xb4\x01\n" +
	"\x16AssignArchetypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\farchetype_id\x18\x02 \x01(\tR\varchetypeId\x12%\n" +
	"\x0earchetype_name\x18\x03 \x01(\tR\rarchetypeName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"9\n" +
	"\x17AssignArchetypeResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"\xb4\x01\n" +
	"\x16UpdateArchetypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\farchetype_id\x18\x02 \x01(\tR\varchetypeId\x12%\n" +
	"\x0earchetype_name\x18\x03 \x01(\tR\rarchetypeName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"9\n" +
	"\x17UpdateArchetypeResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"]\n" +
	"\x17UpdateModalitiesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\n" +
	"modalities\x18\x02 \x03(\v2\x12.user.UserModalityR\n" +
	"modalities\":\n" +
	"\x18UpdateModalitiesResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\")\n" +
	"\x17GetUserReadModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x18GetUserReadModelResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.user.UserReadModelR\x04user\"2\n" +
	" GetUserArchetypeReadModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"!GetUserArchetypeReadModelResponse\x12C\n" +
	"\x0euser_archetype\x18\x01 \x01(\v2\x1c.user.UserArchetypeReadModelR\ruserArchetype\"T\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"u\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"5\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x9b\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\"8\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xf2\x02\n" +
	"\x0fProfileProgress\x12'\n" +
	"\x0ftokens_analyzed\x18\x01 \x01(\x05R\x0etokensAnalyzed\x129\n" +
	"\x19tokens_required_for_first\x18\x02 \x01(\x05R\x16tokensRequiredForFirst\x12;\n" +
	"\x1atokens_required_for_recalc\x18\x03 \x01(\x05R\x17tokensRequiredForRecalc\x12/\n" +
	"\x14days_since_last_calc\x18\x04 \x01(\x05R\x11daysSinceLastCalc\x12*\n" +
	"\x11days_until_recalc\x18\x05 \x01(\x05R\x0fdaysUntilRecalc\x120\n" +
	"\x14is_first_calculation\x18\x06 \x01(\bR\x12isFirstCalculation\x12/\n" +
	"\x13progress_percentage\x18\a \x01(\x01R\x12progressPercentage\"\xfb\x02\n" +
	"\x0eUserStatistics\x12.\n" +
	"\x13total_diary_entries\x18\x01 \x01(\x05R\x11totalDiaryEntries\x12.\n" +
	"\x13total_mood_analyses\x18\x02 \x01(\x05R\x11totalMoodAnalyses\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12)\n" +
	"\x10dominant_emotion\x18\x04 \x01(\tR\x0fdominantEmotion\x12\x1d\n" +
	"\n" +
	"top_topics\x18\x05 \x03(\tR\ttopTopics\x12H\n" +
	"\x12profile_created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10profileCreatedAt\x12R\n" +
	"\x17last_personality_update\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x15lastPersonalityUpdate\"/\n" +
	"\x1dGetUserProfileProgressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x1eGetUserProfileProgressResponse\x121\n" +
	"\bprogress\x18\x01 \x01(\v2\x15.user.ProfileProgressR\bprogress\"*\n" +
	"\x18GetUserStatisticsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x19GetUserStatisticsResponse\x124\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x14.user.UserStatisticsR\n" +
	"statistics2\xb5\a\n" +
	"\vUserService\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12T\n" +
	"\x11UpdateUserProfile\x12\x1e.user.UpdateUserProfileRequest\x1a\x1f.user.UpdateUserProfileResponse\x12N\n" +
	"\x0fAssignArchetype\x12\x1c.user.AssignArchetypeRequest\x1a\x1d.user.AssignArchetypeResponse\x12N\n" +
	"\x0fUpdateArchetype\x12\x1c.user.UpdateArchetypeRequest\x1a\x1d.user.UpdateArchetypeResponse\x12Q\n" +
	"\x10UpdateModalities\x12\x1d.user.UpdateModalitiesRequest\x1a\x1e.user.UpdateModalitiesResponse\x12Q\n" +
	"\x10GetUserReadModel\x12\x1d.user.GetUserReadModelRequest\x1a\x1e.user.GetUserReadModelResponse\x12l\n" +
	"\x19GetUserArchetypeReadModel\x12&.user.GetUserArchetypeReadModelRequest\x1a'.user.GetUserArchetypeReadModelResponse\x12<\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x12c\n" +
	"\x16GetUserProfileProgress\x12#.user.GetUserProfileProgressRequest\x1a$.user.GetUserProfileProgressResponse\x12T\n" +
	"\x11GetUserStatistics\x12\x1e.user.GetUserStatisticsRequest\x1a\x1f.user.GetUserStatisticsResponseB)Z'github.com/kegazani/metachat-proto/userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_user_user_proto_goTypes = []any{
	(*User)(nil),                              // 0: user.User
	(*Archetype)(nil),                         // 1: user.Archetype
	(*UserModality)(nil),                      // 2: user.UserModality
	(*UserReadModel)(nil),                     // 3: user.UserReadModel
	(*UserArchetypeReadModel)(nil),            // 4: user.UserArchetypeReadModel
	(*CreateUserRequest)(nil),                 // 5: user.CreateUserRequest
	(*CreateUserResponse)(nil),                // 6: user.CreateUserResponse
	(*GetUserRequest)(nil),                    // 7: user.GetUserRequest
	(*GetUserResponse)(nil),                   // 8: user.GetUserResponse
	(*UpdateUserProfileRequest)(nil),          // 9: user.UpdateUserProfileRequest
	(*UpdateUserProfileResponse)(nil),         // 10: user.UpdateUserProfileResponse
	(*AssignArchetypeRequest)(nil),            // 11: user.AssignArchetypeRequest
	(*AssignArchetypeResponse)(nil),           // 12: user.AssignArchetypeResponse
	(*UpdateArchetypeRequest)(nil),            // 13: user.UpdateArchetypeRequest
	(*UpdateArchetypeResponse)(nil),           // 14: user.UpdateArchetypeResponse
	(*UpdateModalitiesRequest)(nil),           // 15: user.UpdateModalitiesRequest
	(*UpdateModalitiesResponse)(nil),          // 16: user.UpdateModalitiesResponse
	(*GetUserReadModelRequest)(nil),           // 17: user.GetUserReadModelRequest
	(*GetUserReadModelResponse)(nil),          // 18: user.GetUserReadModelResponse
	(*GetUserArchetypeReadModelRequest)(nil),  // 19: user.GetUserArchetypeReadModelRequest
	(*GetUserArchetypeReadModelResponse)(nil), // 20: user.GetUserArchetypeReadModelResponse
	(*ListUsersRequest)(nil),                  // 21: user.ListUsersRequest
	(*ListUsersResponse)(nil),                 // 22: user.ListUsersResponse
	(*LoginRequest)(nil),                      // 23: user.LoginRequest
	(*LoginResponse)(nil),                     // 24: user.LoginResponse
	(*RegisterRequest)(nil),                   // 25: user.RegisterRequest
	(*RegisterResponse)(nil),                  // 26: user.RegisterResponse
	(*ProfileProgress)(nil),                   // 27: user.ProfileProgress
	(*UserStatistics)(nil),                    // 28: user.UserStatistics
	(*GetUserProfileProgressRequest)(nil),     // 29: user.GetUserProfileProgressRequest
	(*GetUserProfileProgressResponse)(nil),    // 30: user.GetUserProfileProgressResponse
	(*GetUserStatisticsRequest)(nil),          // 31: user.GetUserStatisticsRequest
	(*GetUserStatisticsResponse)(nil),         // 32: user.GetUserStatisticsResponse
	(*timestamppb.Timestamp)(nil),             // 33: google.protobuf.Timestamp
}
var file_user_user_proto_depIdxs = []int32{
	33, // 0: user.User.created_at:type_name -> google.protobuf.Timestamp
	33, // 1: user.User.updated_at:type_name -> google.protobuf.Timestamp
	33, // 2: user.Archetype.assigned_at:type_name -> google.protobuf.Timestamp
	33, // 3: user.UserReadModel.created_at:type_name -> google.protobuf.Timestamp
	33, // 4: user.UserReadModel.updated_at:type_name -> google.protobuf.Timestamp
	33, // 5: user.UserArchetypeReadModel.assigned_at:type_name -> google.protobuf.Timestamp
	33, // 6: user.UserArchetypeReadModel.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: user.CreateUserResponse.user:type_name -> user.User
	0,  // 8: user.GetUserResponse.user:type_name -> user.User
	0,  // 9: user.UpdateUserProfileResponse.user:type_name -> user.User
	0,  // 10: user.AssignArchetypeResponse.user:type_name -> user.User
	0,  // 11: user.UpdateArchetypeResponse.user:type_name -> user.User
	2,  // 12: user.UpdateModalitiesRequest.modalities:type_name -> user.UserModality
	0,  // 13: user.UpdateModalitiesResponse.user:type_name -> user.User
	3,  // 14: user.GetUserReadModelResponse.user:type_name -> user.UserReadModel
	4,  // 15: user.GetUserArchetypeReadModelResponse.user_archetype:type_name -> user.UserArchetypeReadModel
	0,  // 16: user.ListUsersResponse.users:type_name -> user.User
	33, // 17: user.UserStatistics.profile_created_at:type_name -> google.protobuf.Timestamp
	33, // 18: user.UserStatistics.last_personality_update:type_name -> google.protobuf.Timestamp
	27, // 19: user.GetUserProfileProgressResponse.progress:type_name -> user.ProfileProgress
	28, // 20: user.GetUserStatisticsResponse.statistics:type_name -> user.UserStatistics
	7,  // 21: user.UserService.GetUser:input_type -> user.GetUserRequest
	9,  // 22: user.UserService.UpdateUserProfile:input_type -> user.UpdateUserProfileRequest
	11, // 23: user.UserService.AssignArchetype:input_type -> user.AssignArchetypeRequest
	13, // 24: user.UserService.UpdateArchetype:input_type -> user.UpdateArchetypeRequest
	15, // 25: user.UserService.UpdateModalities:input_type -> user.UpdateModalitiesRequest
	17, // 26: user.UserService.GetUserReadModel:input_type -> user.GetUserReadModelRequest
	19, // 27: user.UserService.GetUserArchetypeReadModel:input_type -> user.GetUserArchetypeReadModelRequest
	21, // 28: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	23, // 29: user.UserService.Login:input_type -> user.LoginRequest
	25, // 30: user.UserService.Register:input_type -> user.RegisterRequest
	29, // 31: user.UserService.GetUserProfileProgress:input_type -> user.GetUserProfileProgressRequest
	31, // 32: user.UserService.GetUserStatistics:input_type -> user.GetUserStatisticsRequest
	8,  // 33: user.UserService.GetUser:output_type -> user.GetUserResponse
	10, // 34: user.UserService.UpdateUserProfile:output_type -> user.UpdateUserProfileResponse
	12, // 35: user.UserService.AssignArchetype:output_type -> user.AssignArchetypeResponse
	14, // 36: user.UserService.UpdateArchetype:output_type -> user.UpdateArchetypeResponse
	16, // 37: user.UserService.UpdateModalities:output_type -> user.UpdateModalitiesResponse
	18, // 38: user.UserService.GetUserReadModel:output_type -> user.GetUserReadModelResponse
	20, // 39: user.UserService.GetUserArchetypeReadModel:output_type -> user.GetUserArchetypeReadModelResponse
	22, // 40: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	24, // 41: user.UserService.Login:output_type -> user.LoginResponse
	26, // 42: user.UserService.Register:output_type -> user.RegisterResponse
	30, // 43: user.UserService.GetUserProfileProgress:output_type -> user.GetUserProfileProgressResponse
	32, // 44: user.UserService.GetUserStatistics:output_type -> user.GetUserStatisticsResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
